### ISSUE TITLE
Functions v2 ListLocations is failing in REGAPIC

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#10387]
The smoke test is failing with an exception:

Failed: System.InvalidOperationException: Type registry has no descriptor for type name 'google.cloud.functions.v2.LocationMetadata'
   at Google.Protobuf.JsonParser.MergeAny(IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.<>c.<.cctor>b__41_6(JsonParser parser, IMessage message, JsonTokenizer tokenizer)

Investigating...

**Comment by jskeet** [comment]
This will be resolved by the Functions team republishing their API. There's a deeper underlying issue with Any+REGAPIC, but that's much bigger than this...

**Comment by jskeet** [comment]
Reported internally as b/283396160
