### ISSUE TITLE
Google.Cloud.SecretManager.V1 doesn't support the same filters as `gcloud secrets list`

### ISSUE THREAD

**Issue by neotrow** [googleapis/google-cloud-dotnet#10639]
I'm trying to filter secrets based on assigned labels. 

Let's assume I have a secret that has the label `label1`. 

With gcloud I can do the following:
`gcloud secrets list --filter="labels.list():label1"`

And it will return all the secrets that have the `label1` assigned to them. 

The documentation also suggests the following:
`gcloud secrets list --filter="labels.label1:*"`

But this will not work if the label has no value. 

When I use the `Google.Cloud.SecretManager.V1`  with the following request:
```
ListSecretsRequest request = new ListSecretsRequest
{
    ParentAsProjectName = ProjectName.FromProject("projectname"),
    Filter = "labels.list():label1",
};
```

I get the following exception:

```
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="InvalidArgument", Detail="syntax error at line 1, column 11, token '('")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.SecretManager.V1.SecretManagerService.SecretManagerServiceClient.ListSecrets(ListSecretsRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass12_0.<WithCallSettingsOverlay>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Api.Gax.Grpc.GrpcPagedEnumerable`3.AsRawResponses()+MoveNext()
```

Why does this filter not work? And is there another way to filter the secrets based on the labels they have? (And also supporting empty values for labels) 

Many thanks!

**Comment by amanda-tarafa** [comment]
These questions are better suited for the Secret Manager API team. We only make certain that .NET Google Client Libraries (including Google.Cloud.SecretManager.V1) accurately represent Google Cloud APIs but we have little knowledge about each individual API feature set. Please follow one of the routes in https://cloud.google.com/secret-manager/docs/getting-support, they'll be able to help faster.

I'll be closing this issue now as there's not much more we can do on this repo. If you have issues with the library itself, or find that it's missing a feature clearly supported by the API, then we'll be happy to look into it.
