### ISSUE TITLE
Google.Cloud.Storage.V1 NetworkInformationException: Permission denied

### ISSUE THREAD

**Issue by CADBIMDeveloper** [googleapis/google-cloud-dotnet#11336]
Hi experts,

I have a weird issue. My application is running in a google cloud run docker container:
```
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
...
RUN dotnet publish ...
...
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
...
ENTRYPOINT ["dotnet", ...]
```

Running
```cs
await client.GetObjectAsync(bucket, objectName);
```
I'm facing with the following exception:
```
System.Net.NetworkInformation.NetworkInformationException (13): Permission denied
 at Google.Apis.Http.ConfigurableMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
 at Google.Apis.Auth.OAuth2.Requests.RequestExtensions.PostFormAsync(Object request, HttpClient httpClient, String url, AuthenticationHeaderValue authenticationHeaderValue, IClock clock, ILogger logger, CancellationToken taskCancellationToken)
 at Google.Apis.Auth.OAuth2.ServiceAccountCredential.RequestAccessTokenAsync(CancellationToken taskCancellationToken)
 at Google.Apis.Auth.OAuth2.TokenRefreshManager.RefreshTokenAsync()
 at Google.Apis.Auth.TaskExtensions.<>c__DisplayClass0_0`1.<<WithCancellationToken>g__ImplAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
 at Google.Apis.Auth.OAuth2.TokenRefreshManager.GetAccessTokenForRequestAsync(CancellationToken cancellationToken)
 at Google.Apis.Auth.OAuth2.ServiceAccountCredential.GetAccessTokenForRequestAsync(String authUri, CancellationToken cancellationToken)
 at Google.Apis.Auth.OAuth2.ServiceCredential.GetAccessTokenWithHeadersForRequestAsync(String authUri, CancellationToken cancellationToken)
 at Google.Apis.Auth.OAuth2.ServiceCredential.InterceptAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at Google.Apis.Http.ConfigurableMessageHandler.CredentialInterceptAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at Google.Apis.Http.ConfigurableMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
 at Google.Apis.Requests.ClientServiceRequest`1.ExecuteUnparsedAsync(CancellationToken cancellationToken)
 at Google.Apis.Requests.ClientServiceRequest`1.ExecuteAsync(CancellationToken cancellationToken)
 at ...
```

Sign async works both in .Net7 and .Net8
```cs
await urlSigner.SignAsync(...);
```

Downgrading to .Net 7.0 resolves this issue.

I can't reproduce this issue locally, everything works as expected on my Win10 and Ubuntu 22 machines...

#### Environment details

  - OS: Linux inside a docker container in Google Cloud Run environment
  - .NET version: 8
  - Package name and version: Google.Cloud.Storage.V1, 4.7.0

**Comment by jskeet** [comment]
> I have a weird issue.

That does indeed sound very odd. We'll try to reproduce it and get back to you as soon as we can.

> Sign async works both in .Net7 and .Net8

That doesn't surprise me, given the error - it doesn't require any network access.

@amanda-tarafa Are you happy to have a look at this while I'm away? I can look into it tomorrow otherwise.

**Comment by amanda-tarafa** [comment]
The error is happening when requesting the ServiceAccountCredential access token, not when sending the Storage request so I'd expect we can reproduce without the Google.Cloud.Storage.V1 dependency, and even without the Google.Apis.Auth dependency which handles Auth for Google .NET client libraries.

Can I ask you to execute the following code in your container, targetting .NET 8? Note that there are no Google library dependencies needed here. This code is very similar to what's executed for fetching a service account access token, except that I'm using a bad request. I want to make certain that there's nothing in the .NET 8 container stoping us from reaching the token endpoint.

This code will fail regardless, but, if we are able to reach the token endpoint we should see an HttpStatus.BadRequest (400) error and we'll have to look further in the Google.Apis.Auth library most likely. If we get the `NetworkInformationException` then this error is unrelated to Google .NET client libraries and possibly an issue with .NET 8 support in Cloud Run or similar, in that case, we would point you to the right support channels.

```chsarp
            var tokenEndpoint = "https://oauth2.googleapis.com/token";
            var content = new FormUrlEncodedContent(
                new List<KeyValuePair<string, string>>
                {
                    new KeyValuePair<string, string> ("assertion", "testing 1, 2, 3")
                });

            using HttpClient client = new HttpClient();
            var response = await client.PostAsync(tokenEndpoint, content);
            response.EnsureSuccessStatusCode();
```

**Comment by CADBIMDeveloper** [comment]
Hi @amanda-tarafa ,

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMV6S90FDM0G", Request id "0HMV6S90FDM0G:00000001": An unhandled exception was thrown by the application.
      System.Net.NetworkInformation.NetworkInformationException (13): Permission denied
         at System.Net.NetworkInformation.NetworkChange.CreateSocket()
         at System.Net.NetworkInformation.NetworkChange.add_NetworkAddressChanged(NetworkAddressChangedEventHandler value)
         at System.Net.Http.HttpConnectionPoolManager.StartMonitoringNetworkChanges()
         at System.Net.Http.HttpConnectionPool.HandleAltSvc(IEnumerable`1 altSvcHeaderValues, Nullable`1 responseAge)
         at System.Net.Http.HttpConnectionPool.ProcessAltSvc(HttpResponseMessage response)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at TestGoogleCloudBucketAccessWeb.Services.Execute11336() in /app/Services.cs:line 36
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

So it's `NetworkInformationException`. Where to ask about this?

**Comment by amanda-tarafa** [comment]
I'd start by going through the [Cloud Run support channels](https://cloud.google.com/run/docs/support) they should be able to help you.

I did a quick look around and Cloud Run's build packs still [do not support .NET 8](https://cloud.google.com/docs/buildpacks/builders#buildergoogle-22_supported_languages), only up to .NET 7.

That said, and as per documentation, [you should be able to use any container](https://cloud.google.com/run/docs/building/containers) as long as it respects the [container contract](https://cloud.google.com/run/docs/container-contract). An avenue for you could be to check that your container does respect the container contract. Also follow the Cloud Run support channels if you need help with that.

I'll be closing this issue now as there's not much else we can do on our side, this is definetely not a library related issue.

**Comment by CADBIMDeveloper** [comment]
Hi @amanda-tarafa , thank you!

**Comment by TDC-mobstation** [comment]
@CADBIMDeveloper We're running into the same issue, did you manage to found a way forward?

**Comment by CADBIMDeveloper** [comment]
Thanks!
