### ISSUE TITLE
dotnet 8 Docker Image:  System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies

### ISSUE THREAD

**Issue by andmos** [googleapis/google-cloud-dotnet#11779]
As stated here: https://github.com/googleapis/google-cloud-dotnet/issues/5828#issuecomment-1956118634

#### Environment details

  - OS: mcr.microsoft.com/dotnet/aspnet:8.0.2 container image, so Debian 12 Bookworm.
  - .NET version: 8.0.2
  - Package name and version: Possibly `google.cloud.storage.v1/4.8.0` or `serilog.sinks.googlecloudlogging/3.4.0`, error happens runtime on GCP Cloud Run and GCP App Engine.

#### Steps to reproduce

We have two dotnet projects deployed as Docker images to GCP App Engine for the first, GCP Cloud Run for the second.
After updating the container images from dotnet 7 to dotnet 8 (both SDK and runtime) we're getting 
`System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies.`
from both projects. 
<details><summary>Stacktrace</summary>
<p>
```
ERROR: (gcloud.app.deploy) Error Response: [9] An internal error occurred while processing task /app-engine-flex/flex_await_healthy/flex_await_healthy>2024-02-21T08:44:03.417Z8257.wa.2: Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/app/runtimes/linux/native/libdl.so: cannot open shared object file: No such file or directory
/app/runtimes/linux-x64/native/libdl.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/libdl.so: cannot open shared object file: No such file or directory
/app/libdl.so: cannot open shared object file: No such file or directory
/app/runtimes/linux/native/liblibdl.so: cannot open shared object file: No such file or directory
/app/runtimes/linux-x64/native/liblibdl.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/liblibdl.so: cannot open shared object file: No such file or directory
/app/liblibdl.so: cannot open shared object file: No such file or directory
/app/runtimes/linux/native/libdl.so.so: cannot open shared object file: No such file or directory
/app/runtimes/linux-x64/native/libdl.so.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/libdl.so.so: cannot open shared object file: No such file or directory
/app/libdl.so.so: cannot open shared object file: No such file or directory
/app/runtimes/linux/native/liblibdl.so.so: cannot open shared object file: No such file or directory
/app/runtimes/linux-x64/native/liblibdl.so.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.2/liblibdl.so.so: cannot open shared object file: No such file or directory
/app/liblibdl.so.so: cannot open shared object file: No such file or directory
   at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags)
   at Grpc.Core.Internal.UnmanagedLibrary.LoadLibraryPosix(Func`3 dlopenFunc, Func`1 dlerrorFunc, String libraryPath, String& errorMsg)
   at Grpc.Core.Internal.UnmanagedLibrary.PlatformSpecificLoadLibrary(String libraryPath, String& errorMsg)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.GrpcCore.GrpcCoreAdapter.CreateChannelImpl(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
   at Google.Api.Gax.Grpc.GrpcAdapter.CreateChannel(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateChannel(String endpoint, ChannelCredentials credentials)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker()
   at Google.Cloud.Logging.V2.LoggingServiceV2ClientBuilder.BuildImpl()
   at Google.Cloud.Logging.V2.LoggingServiceV2ClientBuilder.Build()
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSink..ctor(GoogleCloudLoggingSinkOptions sinkOptions, MessageTemplateTextFormatter messageTemplateTextFormatter)
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSinkExtensions.GoogleCloudLogging(LoggerSinkConfiguration loggerConfiguration, GoogleCloudLoggingSinkOptions sinkOptions, Nullable`1 batchSizeLimit, Nullable`1 period, Nullable`1 queueLimit, String outputTemplate, LogEventLevel restrictedToMinimumLevel, LoggingLevelSwitch levelSwitch)
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSinkExtensions.GoogleCloudLogging(LoggerSinkConfiguration loggerConfiguration, String projectId, String resourceType, String logName, Dictionary`2 labels, Dictionary`2 resourceLabels, Boolean useSourceContextAsLogName, Boolean useJsonOutput, Boolean useLogCorrelation, String googleCredentialJson, String serviceName, String serviceVersion, Nullable`1 batchSizeLimit, Nullable`1 period, Nullable`1 queueLimit, String outputTemplate, LogEventLevel restrictedToMinimumLevel, LoggingLevelSwitch levelSwitch)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Serilog.Settings.Configuration.ConfigurationReader.CallConfigurationMethods(ILookup`2 methods, IList`1 configurationMethods, Object receiver)
   at Serilog.Settings.Configuration.ConfigurationReader.ApplySinks(LoggerConfiguration loggerConfiguration)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext)
   at Application.Reserve.Web.Program.InitLogging(IConfiguration configuration) in /app/Web/Program.cs:line 59
   at Application.Reserve.Web.Program.Main(String[] args) in /app/Web/Program.cs:line 18

</p>
</details> 

If `Grpc.Core` package is referenced in both runtime-projects, the problem goes away - `Grpc.Net.Client` does not help.

The `Dockerfile` used for GCP App Engine :

```dockerfile
FROM node:14-alpine AS frontend-build
WORKDIR /app

COPY ./frontend/package.json ./
COPY ./frontend/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY ./frontend ./
RUN yarn build

FROM mcr.microsoft.com/dotnet/sdk:8.0.201 AS dotnet-build

WORKDIR /app
COPY ./backend/Directory.Build.props ./
COPY ./backend/Agenter/Epost/Epost.csproj ./Agenter/Epost/
COPY ./backend/Agenter/GoogleCloudPlatform/GoogleCloudPlatform.csproj ./Agenter/GoogleCloudPlatform/
COPY ./backend/Agenter/Intelecom/Intelecom.csproj ./Agenter/Intelecom/
COPY ./backend/Agenter/Rutesøk/Rutesøk.csproj ./Agenter/Rutesøk/
COPY ./backend/Data/Data.csproj ./Data/
COPY ./backend/Domene/Domene.csproj ./Domene/
COPY ./backend/EksterntApi/EksterntApi.csproj ./EksterntApi/
COPY ./backend/Identity/Identity.csproj ./Identity/
COPY ./backend/Import/Import.csproj ./Import/
COPY ./backend/Logikk/Logikk.csproj ./Logikk/
COPY ./backend/Web/Web.csproj ./Web/

RUN dotnet restore Web/Web.csproj

COPY ./backend ./
COPY --from=frontend-build /app/dist ./Web/wwwroot
RUN dotnet publish Web/Web.csproj -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:8.0.2 AS runtime
WORKDIR /app
RUN apt update && apt install -y apt-utils libgdiplus libc-dev

COPY --from=dotnet-build /app/out .
ENTRYPOINT ["dotnet", "Application.Reserve.Web.dll", "--urls", "http://0.0.0.0:8080"]
```

The only "pure" Google Cloud packages we depend on are 
```
<PackageReference Include="Google.Cloud.Storage.V1" Version="4.8.0" />
<PackageReference Include="Serilog.Sinks.GoogleCloudLogging" Version="3.4.0" />
```

**Comment by andmos** [comment]
The answer was staring me in the face 🤦 I forgot to bump the `Serilog.Sinks.GoogleCloudLogging` package and the stacktrace pointed to it. After upgrading to version 5.0.0 and removing Grpc.Core, the problem went away. Closing.
