### ISSUE TITLE
Local Development: URL Signing - Host is down (169.254.169.254:80)

### ISSUE THREAD

**Issue by SteGaff7** [googleapis/google-cloud-dotnet#12210]
#### Environment details

  - OS: macOS Sonoma 14.1.2
  - .NET version: 7.0
  - Package name and version: Google.Cloud.Storage.V1 4.7.0

#### Steps to reproduce

I am having an issue signing URLs with the Google Storage client library in a local development environment. I have familiarised myself with previous issues in this area: https://github.com/googleapis/google-cloud-dotnet/issues/1056, https://github.com/googleapis/google-cloud-dotnet/issues/2316, https://github.com/googleapis/google-cloud-dotnet/issues/2411, and I understand the issues for the most part, but I wanted to clarify a few things and make sure I am not missing something.

I am currently in the processing of migrating from service account keys to attaching service accounts to cloud run instances. I am then impersonating this service account for local development, and it seems to be working fine for the most part with the exception of signing public URLs. I am using the suggested compute credential as a workaround for creating a URL signer from a credential:

```        
        var credential = new ComputeCredential();
        var urlSigner = UrlSigner.FromCredential(credential);

        return await urlSigner.SignAsync(
            bucketName,
            path,
            TimeSpan.FromDays(ProfileUrlExpireDays),
            HttpMethod.Get);
```

This runs fine on GCP cloud run using a service account with the following roles:

- Cloud Datastore User
- Firebase Authentication Admin
- Service Account Token Creator
- Storage Object User

However, when running locally impersonating the same service account, I get the following error:

```
Host is down (169.254.169.254:80)
      System.Net.Http.HttpRequestException: Host is down (169.254.169.254:80)
       ---> System.Net.Sockets.SocketException (64): Host is down
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
         at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Net.Http.HttpConnectionPool.<>c.<CheckForHttp11ConnectionInjection>b__77_0(ValueTuple`2 state)
         at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
         at System.Threading.QueueUserWorkItemCallback`1.Execute()
         at System.Threading.ThreadPoolWorkQueue.Dispatch()
         at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
         at System.Threading.Thread.StartCallback()
      --- End of stack trace from previous location ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Google.Apis.Http.ConfigurableMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Google.Apis.Auth.OAuth2.ComputeCredential.FetchDefaultServiceAccountEmailAsync()
         at Google.Cloud.Storage.V1.UrlSigner.<>c__DisplayClass15_0.<<FromCredential>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Google.Cloud.Storage.V1.UrlSigner.BlobSignerProvider.<>c__DisplayClass3_0.<<-ctor>g__SafeBlobSignerProvider|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Google.Cloud.Storage.V1.UrlSigner.V4Signer.SignAsync(RequestTemplate requestTemplate, Options options, BlobSignerProvider blobSignerProvider, IClock clock, CancellationToken cancellationToken)
         at Google.Cloud.Storage.V1.UrlSigner.SignAsync(String bucket, String objectName, TimeSpan duration, HttpMethod httpMethod, Nullable`1 signingVersion, CancellationToken cancellationToken)
```

My understanding is that I cannot access the metadata server outside of the GCP environment and this is needed for some aspect of the compute credential creation? 

I understand this is largely a GCP rather than a google dotnet issue. However, is there any workaround for this so that I can use the same code in both GCP and local environments without having to download service account keys, since this is the main reason for this refactor?

Thanks!

**Comment by jskeet** [comment]
Yes, the problem is that you're using a `ComputeCredential`. That means "talk to the metadata server at 169.254.169.254 to obtain access tokens etc". I'm not quite sure what you mean by "when running locally impersonating the same service account" - but you shouldn't expect a `ComputeCredential` to work outside GCP.

When you're running locally, what credential do you *want* to use? You can't use the GCP metadata servers, and it sounds like you don't want to download service account credentials, so what credential would you expect to be used?

**Comment by SteGaff7** [comment]
I attach a service account to the cloud run instance when deploying on GCP. For local development, I am impersonating this service account and using the application default credentials, which will then be the service account. This allows me to avoid downloading the service account keys. 

Ideally, I can just sign the URLs with this service account by:
```
        var urlSigner = UrlSigner.FromCredential(await GoogleCredential.GetApplicationDefaultAsync());
```

but this doesn't work, and as far as I understand, it is because it is a Google Credential rather than a Service Account Credential? 

I might be missing something obvious here which would be great, but I think I am understanding correctly?

**Comment by SteGaff7** [comment]
The only thing I have done for impersonation is running this gcloud command from [docs](https://cloud.google.com/docs/authentication/provide-credentials-adc#service-account)
` gcloud auth application-default login --impersonate-service-account SERVICE_ACCT_EMAIL `

I will follow up with the specific issue on your second question.

**Comment by jskeet** [comment]
Okay, having run that `gcloud` command myself just now, you should end up with default credentials of a `GoogleCredential` wrapping an `ImpersonatedCredential`.

It looks like that should already be working in 4.7.0 (your `UrlSigner.FromCredential` call) - so I'll be interested to see what's going wrong. It's possible that our `ImpersonatedCredential` code needs to change. (Trying that credential locally with an entirely different API has failed with an OAuth error, which is interesting...)

**Comment by SteGaff7** [comment]
I haven't been able to recreate the issue I was having, so I must have been doing something wrong and over complicated my solution as a result! 

Returning the code to:
```
var urlSigner = UrlSigner.FromCredential(await GoogleCredential.GetApplicationDefaultAsync());
```
 has fixed issues I was having and works both in GCP and locally with the impersonated service account. Thanks for the quick responses and quick replies, I think it is okay to close this now.

**Comment by SteGaff7** [comment]
Seeing your recent comment now. I too end up with GoogleCredential which seems to work fine in the URL signer.

**Comment by jskeet** [comment]
Glad it's all working now. Using the default app credentials is definitely a better way to go than explicitly creating compute credentials. If it *stops* working again, please file a new issue with the code and the precise error.

**Comment by SteGaff7** [comment]
Thanks Amanda, yes, I think it might have been a role that had not yet propagated or a role that I had not yet added. Thanks for the help, and if there are further issues, I will let you know.
