### ISSUE TITLE
[Firestore] [Question] Unable converter map to List/Dictionary

### ISSUE THREAD

**Issue by Hyrwing** [googleapis/google-cloud-dotnet#13169]
Hello, 

I'm trying to convert a Colletion _clients_ to an object _Client_. 

That clients collection has a field _accounts_ which is a map.

![image](https://github.com/googleapis/google-cloud-dotnet/assets/4070341/fc6594e2-dca8-4b54-8c53-351cd65ab590)

So for _Accounts_ property in the object bellow. I have tried some different approaches and all of them are returning parsing exceptions. **How can I convert that structure to an C# object?**

`public required Dictionary<string, Account> Accounts { get; set; }`

`public required List<Account> Accounts { get; set; }`

Following [Data Model](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Firestore/latest/datamodel) it should be the first option using `Dictionary` structure.

Code snippet 
```dotnet
var values = snapshot.Documents.Where(d => d.Exists).Select(d => 
{
    var data = d.ConvertTo<Client>();
    data.Id = d.Id;

    return data;
});
```

Object
```dotnet
[FirestoreData]
public class Client : FirestoreEntity
{
    [FirestoreProperty("cnpjCpf")]
    public required string CnpjCpf { get; set; }

    [FirestoreProperty("name")]
    public required string Name { get; set; }

    [FirestoreProperty("accounts")]
    public required Dictionary<string, Account> Accounts { get; set; }
}

[FirestoreData] //Added as recommend by Jon
public class Account
{
    [FirestoreProperty("bankId")]
    public required DocumentReference BankId { get; set; }

    [FirestoreProperty("checkingAccount")]
    public required string CheckingAccount { get; set; }
}
```

Stack Traces:

```
   Unable to create converter for type Account

   at Google.Cloud.Firestore.Converters.ConverterCache.CreateConverter(Type targetType)
   at Google.Cloud.Firestore.Converters.ConverterCache.<>c.<GetConverter>b__1_0(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Google.Cloud.Firestore.Converters.ConverterCache.GetConverter(Type targetType)
   at Google.Cloud.Firestore.SerializationContext.GetConverter(Type targetType)
   at Google.Cloud.Firestore.ValueDeserializer.Deserialize(IDeserializationContext context, Value value, Type targetType)
   at Google.Cloud.Firestore.Converters.DictionaryConverter`1.DeserializeMap(IDeserializationContext context, IDictionary`2 values)
   at Google.Cloud.Firestore.Converters.ConverterBase.DeserializeValue(IDeserializationContext context, Value value)
   at Google.Cloud.Firestore.ValueDeserializer.Deserialize(IDeserializationContext context, Value value, Type targetType)
   at Google.Cloud.Firestore.Converters.AttributedTypeConverter.AttributedProperty.SetValue(IDeserializationContext context, Value value, Object target)
   at Google.Cloud.Firestore.Converters.AttributedTypeConverter.DeserializeMap(IDeserializationContext context, IDictionary`2 values)
   at Google.Cloud.Firestore.ValueDeserializer.DeserializeMap(IDeserializationContext context, IDictionary`2 values, Type targetType)
   at Google.Cloud.Firestore.DocumentSnapshot.ConvertTo[T]()
   at XPayD.Repositories.FirestoreRepository`1.<>c__5`1.<GetAllAsync>b__5_1(DocumentSnapshot d) in D:\Git\xpayd\functions\Core\XPayD.Repositories\FirestoreRepository.cs:line 33
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

``` 
   Unable to convert map value to System.Collections.Generic.List`1[Account]

   at Google.Cloud.Firestore.Converters.ConverterBase.DeserializeMap(IDeserializationContext context, IDictionary`2 values)
   at Google.Cloud.Firestore.Converters.ConverterBase.DeserializeValue(IDeserializationContext context, Value value)
   at Google.Cloud.Firestore.ValueDeserializer.Deserialize(IDeserializationContext context, Value value, Type targetType)
   at Google.Cloud.Firestore.Converters.AttributedTypeConverter.AttributedProperty.SetValue(IDeserializationContext context, Value value, Object target)
   at Google.Cloud.Firestore.Converters.AttributedTypeConverter.DeserializeMap(IDeserializationContext context, IDictionary`2 values)
   at Google.Cloud.Firestore.ValueDeserializer.DeserializeMap(IDeserializationContext context, IDictionary`2 values, Type targetType)
   at Google.Cloud.Firestore.DocumentSnapshot.ConvertTo[T]()
   at XPayD.Repositories.FirestoreRepository`1.<>c__5`1.<GetAllAsync>b__5_1(DocumentSnapshot d) in D:\Git\xpayd\functions\Core\XPayD.Repositories\FirestoreRepository.cs:line 33
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

**Comment by jskeet** [comment]
You haven't put `[FirestoreData]` on the `Account` class. That's why it can't create the converter. But looking at the fields, I suspect that would only work for a *single* Account, not a list or map of them. If you want multiple accounts under a document, I suggest you have an `accounts` *collection* nested inside it.

**Comment by Hyrwing** [comment]
Jon, appreciate your answer. I have added the _[FirestoreData]_ and now I'm getting:
`Unable to convert reference value to Account` 
In this case seems like the reference for _bankId_ is the issue. 
I'll change the structure to be a collection as you mentioned. I've misunderstood map structure.

Thank you!

**Comment by jskeet** [comment]
> In this case seems like the reference for bankId is the issue.

No, it's whatever you're trying to convert to Account. At the moment it's hard to tell what your current code looks like though.

**Comment by Hyrwing** [comment]
It's pretty much the same code above, only added the `[FirestoreData]` as you mentioned. Also I did a test removing that `DocumentReference` field and now it's complaining on some string value which I would assume it's that `checkingAccount`.

`Unable to convert string value to Account`

```
[FirestoreData]
public class Account
{
    //[FirestoreProperty("bankId")]
    //public required DocumentReference BankId { get; set; }

    [FirestoreProperty("checkingAccount")]
    public required string CheckingAccount { get; set; }
}
```

**Comment by jskeet** [comment]
> It's pretty much the same code above, only added the [FirestoreData] as you mentioned. 

Okay, so I would suggest that instead of that, you change your `Accounts` property to just be of type `Account`. At the moment it's trying to convert the map into a dictionary of accounts, and that's not what your data has. Basically while the shape of your data doesn't match the shape of your code, you're going to be stuck.

**Comment by Hyrwing** [comment]
Yep, that does the trick. So _map_ structure is really converted to an object and not Dictionary. Thank you!

**Comment by jskeet** [comment]
>  So map structure is really converted to an object and not Dictionary. Thank you!

Well I suspect you *can* have a map where each field value is *also* a map. But in the screenshot of the data you showed, each of the map keys was really a field within Account - I don't know what you'd expect the key in the `Dictionary<string, Account>` to be. Basically you were missing a level of mapping.

**Comment by Hyrwing** [comment]
I misunderstood the [Data Model](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Firestore/latest/datamodel#data-types) Map data type. But it's all good, appreciate your help.

**Comment by jskeet** [comment]
Great - I'll close this issue now as it sounds like you're sorted.
