### ISSUE TITLE
SubscriberClientImpl.DisposeAsync throws exception

### ISSUE THREAD

**Issue by anabnich** [googleapis/google-cloud-dotnet#13647]
#### Environment details

  - OS: Mac
  - .NET version: .NET 8
  - Package name and version: 3.18.0

#### Steps to reproduce

  1. Create DI container
  2. Register a pubsub subscription
  3. Throw an exception in a class which is instantiated via DI injection.

**result:**

Unhandled exception. System.InvalidOperationException: Can only stop a started instance.
   at Google.Api.Gax.GaxPreconditions.CheckState(Boolean condition, String message)
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.StopAsync(CancellationToken hardStopToken)
   at Google.Cloud.PubSub.V1.SubscriberClient.StopAsync(TimeSpan timeout)
   at Google.Cloud.PubSub.V1.SubscriberClientImpl.DisposeAsync()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>g__DisposeAsync|21_0(Object o)
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at WebApplication.Program.Main(String[] args) 
   
**Expected result:**
DisposeAsync does not throw an exception if it hasn't been started yet. The constructor exception will be caught in DI container and logged.

**Comment by jskeet** [comment]
Thanks for reporting this. We'll look into it.

**Comment by anabnich** [comment]
Thanks for the fix. Which release will this be in?

**Comment by jskeet** [comment]
We've now released version 3.19.0 which contains this fix.
