### ISSUE TITLE
Google.Cloud.Firestore.Admin.V1 - ListIndexes - Permission denied on resource project

### ISSUE THREAD

**Issue by SteGaff7** [googleapis/google-cloud-dotnet#13719]
#### Environment details

  - OS: mac OS Sequoia 15.0.1
  - .NET version: net8.0
  - Package name and version: Google.Cloud.Firestore.Admin.V1 - 3.11.0

#### Steps to reproduce

I get the below error message when trying to list or create a Firestore index:
```
Grpc.Core.RpcException: Status(StatusCode="PermissionDenied", Detail="Permission denied on resource project")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Firestore.Admin.V1.FirestoreAdmin.FirestoreAdminClient.ListIndexes(ListIndexesRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass12_0.<WithCallSettingsOverlay>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Api.Gax.Grpc.GrpcPagedEnumerable`3.AsRawResponses()+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at IndexApp.Program.Main(String[] args) in /Users/stephengaffney/Repos/index-app/IndexApp/IndexApp/Program.cs:line 13
```

My code is basic as I am just exploring the feasibility of dynamically creating composite indexes:

```
using Google.Cloud.Firestore.Admin.V1;

namespace IndexApp
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var firestoreAdminClient = await FirestoreAdminClient.CreateAsync();
            var databases = await firestoreAdminClient.ListDatabasesAsync("projects/my-project");

            var indexes = firestoreAdminClient.ListIndexes("projects/my-project/databases/(default)");
            var first = indexes.FirstOrDefault();
        }
    }
}
```

I am using a default application credential file and specifying the path using GOOGLE_APPLICATION_CREDENTIALS env var and I am retrieving the databases without issue on line 10. My service account has all the permissions I could think of to try to avoid this error:
- Cloud Datastore Index Admin
- Cloud Datastore Owner
- Cloud Storage for Firebase Admin
- Firebase Admin
- Firestore Service Agent

Which makes me think that there is an issue or I am missing something obvious?

Thanks
Stephen

**Comment by jskeet** [comment]
The `ListIndexes` call accepts a collection group, not just a project - but you can specify `-` to search for indexes across all collection groups. I advise using the overloads accepting resource name classes where possible, as it helps to find this sort of thing early.

Here's an example which works for me - please give it a try:

```csharp
using Google.Api.Gax.ResourceNames;
using Google.Cloud.Firestore.Admin.V1;

if (args.Length != 1)
{
    Console.WriteLine("Please specify the project ID");
    return;
}

string projectId = args[0];

var firestoreAdminClient = await FirestoreAdminClient.CreateAsync();
var databases = await firestoreAdminClient.ListDatabasesAsync(new ProjectName(projectId));
Console.WriteLine("Databases:");
foreach (var database in databases.Databases)
{
    Console.WriteLine(database.Name);
}

var indexes = firestoreAdminClient.ListIndexesAsync(new CollectionGroupName(projectId, "(default)", "-"));
Console.WriteLine("Indexes:");
await foreach (var index in indexes)
{
    Console.WriteLine(index.Name);
}
```

**Comment by jskeet** [comment]
(I don't *think* we've got any samples creating indexes with the Firestore Admin library, but https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.Firestore/Google.Cloud.Firestore.IntegrationTests/FirestoreFixture.cs is used in our integration tests and can be used as a starting point.)

**Comment by SteGaff7** [comment]
Thanks Jon for the quick reply, I will test this out and get back.

**Comment by SteGaff7** [comment]
Hi Jon, I tested that and it works as expected, I am also able to create indexes as required so that is great. 

I think the confusion came from the class name `CollectionGroupName` - I thought this was only used for collection group composite indexes and not collection indexes. I had previously used the API explorer [here](https://cloud.google.com/firestore/docs/reference/rest/v1beta1/projects.databases.indexes/list) and used the same `parent` string for this class call. 

Thanks for your help

**Comment by jskeet** [comment]
Right - I don't honestly know the reasons for the difference between the REST API and the gRPC API (which is what the library is based on) - you can look at [the proto defining the gRPC API](https://github.com/googleapis/googleapis/blob/master/google/firestore/admin/v1/firestore_admin.proto) and there's no sign of that REST call. However, so long as it's working for you, all is well :)
