### ISSUE TITLE
Update Google.Api.Gax.Grpc dependency in Google.Cloud.Firestore.V1

### ISSUE THREAD

**Issue by DenSmoke** [googleapis/google-cloud-dotnet#2879]
Google.Cloud.Firestore.V1 still uses Google.Api.Gax.Grpc 2.5.0 version and I get error when project is targeted to .NET Core 3.0.

```
System.TypeInitializationException
  HResult=0x80131534
  Message = The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception.
  Source = Microsoft.Extensions.PlatformAbstractions
  Stack trace:
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Default()
   at Google.Api.Gax.VersionHeaderBuilder.AppendDotNetEnvironment()
   at Google.Api.Gax.Grpc.ServiceSettingsBase..ctor()
   at Google.Cloud.Firestore.V1.FirestoreSettings..ctor()
   at Google.Cloud.Firestore.V1.FirestoreSettings.GetDefault()
   at Google.Cloud.Firestore.V1.FirestoreClientImpl..ctor(FirestoreClient grpcClient, FirestoreSettings settings)
   at Google.Cloud.Firestore.V1.FirestoreClient.Create(CallInvoker callInvoker, FirestoreSettings settings)
   at Google.Cloud.Firestore.V1.FirestoreClient.Create(Channel channel, FirestoreSettings settings)
   at DpTools.Firebase.InitAsync(CancellationToken ct) in C:\Users\densm\Source\Repos\DenSmoke\TechWiz\DpTools\Firebase.cs:line 62
   at TechWiz.Server.TechWizServer.StartAsync(CancellationToken ct) in C:\Users\densm\Source\Repos\DenSmoke\TechWiz\TechWiz.Server\TechWizServer.cs:line 76
   at TechWiz.Server.Program.Main() in C:\Users\densm\Source\Repos\DenSmoke\TechWiz\TechWiz.Server\Program.cs:line 57
   at TechWiz.Server.Program.<Main>()

Inner exception 1:
TargetParameterCountException: Parameter count mismatch.
```
According to issue https://github.com/googleapis/gax-dotnet/issues/231 problem with .NET Core 3.0 preview was fixed so I added version 2.6.0 package explicitely to avoid error, but it is not very clean solution

**Comment by jskeet** [comment]
The next release of Google.Cloud.Firestore.V1 will depend on Google.Api.Gax.Grpc 2.6.0. Given how simple the workaround is, and how it only affects a *preview* version of .NET Core, I didn't want to do a new release of Google.Cloud.Firestore/Google.Cloud.Firestore.V1 just for that updated dependency.

**Comment by DenSmoke** [comment]
Thanks for fast response
