### ISSUE TITLE
Inserting SpannerParameter.CommitTimestamp into Timestamp column with allow_commit_timestamp fails with exception

### ISSUE THREAD

**Issue by FransBouma** [googleapis/google-cloud-dotnet#2975]
#### Environment details

  - OS: Windows 8.1
  - .NET version: 4.6.2
  - Package name and version: Google.Cloud.Spanner.Data v2.0.0 beta 8

#### Steps to reproduce

I have the following table: (this is all test code, hence the lame names)

``` SQL
CREATE TABLE TypesTab (
        ID INT64 NOT NULL,
        NAME STRING(40),
        DESCRIPTION STRING(MAX),
        FLOATCOL FLOAT64,
        IS_ACTIVE BOOL,
        BYTESCOL BYTES(40),
        IMAGECOL BYTES(MAX),
        TIMESTAMPCOL_AUTO TIMESTAMP OPTIONS (allow_commit_timestamp = true),
        TIMESTAMPCOL TIMESTAMP,
        DATECOL DATE,
) PRIMARY KEY(ID)
```

I'm trying to insert the commit timestamp into the TIMESTAMPCOL_AUTO column. For this repro I use this code:

```c#

private static void InsertTest()
{
	using(var con = new SpannerConnection(CreateConnectionString()))
	{
		Console.WriteLine("Opening connection");
		con.Open();
		Console.WriteLine("Connection opened");

		var cmd = con.CreateCommand();
		cmd.CommandText = @"INSERT INTO `TypesTab` (`ID`, `TIMESTAMPCOL_AUTO`) VALUES (@p1, @p2)";
		cmd.Parameters.Add(new SpannerParameter("@p1", SpannerDbType.Int64, 1));
		cmd.Parameters.Add(new SpannerParameter("@p2", SpannerDbType.Timestamp, SpannerParameter.CommitTimestamp));
		var result = cmd.ExecuteNonQuery();
		Console.WriteLine("Number of rows affected: {0}", result);
	}
}


private static string CreateConnectionString()
{
	return $"Data Source=projects/{ProjectID}/instances/{InstanceID}/databases/{DatabaseID}";
}
```

This results in the following output/ exception:
```
Opening connection
Connection opened

Unhandled Exception: Google.Cloud.Spanner.Data.SpannerException: An invalid argument was sent to Spanner. ---> Grpc.Core.RpcException: Status(StatusCode=InvalidArgument, Detail="Value has type INT64 which cannot be inserted into column TIMESTAMPCOL_AUTO, which
has type TIMESTAMP [at 1:65]\nINSERT INTO `TypesTab` (`ID`, `TIMESTAMPCOL_AUTO`) VALUES (@p1, @p2)\n                                                                ^")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Gcp.GcpClientResponseStream`2.<MoveNext>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.V1.Internal.ExecuteHelper.<WithSessionExpiryChecking>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.V1.SqlResultStream.<ComputeNextAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.V1.SqlResultStream.<MoveNext>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.V1.ReliableStreamReader.<MoveNextAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.V1.ReliableStreamReader.<EnsureInitializedAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.V1.ReliableStreamReader.<NextAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.SpannerTransaction.<>c__DisplayClass36_0.<<Google-Cloud-Spanner-Data-ISpannerTransaction-ExecuteDmlAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.ExecuteHelper.<WithErrorTranslationAndProfiling>d__2`1.MoveNext()
   --- End of inner exception stack trace ---
   at Google.Cloud.Spanner.Data.ExecuteHelper.<WithErrorTranslationAndProfiling>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.EphemeralTransaction.<>c__DisplayClass3_0.<<ExecuteDmlAsync>g__Impl|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.ExecuteHelper.<WithErrorTranslationAndProfiling>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Spanner.Data.SpannerCommand.ExecutableCommand.<ExecuteDmlAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions(Task task)
   at Google.Cloud.Spanner.Data.SpannerCommand.ExecuteNonQuery()
   at SpannerTest.Program.InsertTest() in ************\SpannerTest\Program.cs:line 64
   at SpannerTest.Program.Main(String[] args) in ************\SpannerTest\Program.cs:line 17

Process finished with exit code -532.462.766.
```
I think I followed everything in the docs. The INT64 remark is weird, I don't see what's wrong here. 

TIA.

**Comment by jskeet** [comment]
Thanks for raising this with such a clear repro. I'll look into it now. (Your code looks very similar to the integration test which passes, so I'll be fascinated to find out what's wrong...)

**Comment by jskeet** [comment]
The good news is that I can reproduce it. Now to try to work out why it's failing...

**Comment by jskeet** [comment]
Okay, some progress. It looks like this may be a matter of it not being supported in "regular DML" but only using direct row modifications.

Here's code that *does* work against the same table:

```csharp
var cmd = con.CreateInsertCommand("TypesTab");
cmd.Parameters.Add(new SpannerParameter("ID", SpannerDbType.Int64, 2));
cmd.Parameters.Add(new SpannerParameter("TIMESTAMPCOL_AUTO", SpannerDbType.Timestamp, SpannerParameter.CommitTimestamp));
var result = cmd.ExecuteNonQuery();
Console.WriteLine("Number of rows affected: {0}", result);
```

Assuming I'm right about this, it's something we'd be unable to fix within the C# code. Instead we'd need to document it as a limitation - and file a feature request with the Spanner team to allow it in general DML.

**Comment by jskeet** [comment]
It looks like for regular DML, you need to call the `PENDING_COMMIT_TIMESTAMP` function instead of specifying a parameter value. That's a pity :(
See https://cloud.google.com/spanner/docs/commit-timestamp#dml

**Comment by FransBouma** [comment]
Thanks for looking into this! I missed that piece of documentation as it was right below what I looked at (the example of inserting a row with allow_commit_timestamp). Sorry for that. Well, that function is actually beneficial for us over the SpannerParameter.CommitTimestamp, as our code is a generic ORM library and doesn't have a reference to the ADO.NET provider so we had to pull that CommitTimestamp value through reflection and generating that function call is easy as the whole query is generated :) 

I'll test this out tomorrow but it looks like this is what we're looking for. Thanks for the info/time, as always :) I'll close this for now.

**Comment by jskeet** [comment]
I'll reopen for now, as we need to document this more clearly for C# - in particular, I wasn't aware of it myself, which is embarrassing :)

Glad to have unblocked your code though!

**Comment by FransBouma** [comment]
:) Yeah the documentation is a bit confusing. It starts with 'you need to do 2 things...' https://cloud.google.com/spanner/docs/commit-timestamp and basically doesn't mention that the second thing shown there is non-DML, while a reader could simply think (as did I) that the example shown is illustrating a concept that is equal for non-DML and DML, as the documentation section doesn't mention it's not. Scrolling down you'll run into the remark to do it differently in DML, but as there's no need to read that far if you already found the way to do it (according to the docs), it's unlikely you'd read that. 

One could argue why there's a discrepancy between the two at all, but I guess that's something that would otherwise require a change in spanner which might be harder to get through than a documentation change ;) (E.g. I first had the code insert a NULL into this column as I wrongly assumed it would act like any other DB would: a default clause would be handled when a NULL is inserted and a default clause is present, which isn't the case here, you have to explicitly state something.)

**Comment by jskeet** [comment]
Right. I can raise the general Cloud Spanner docs internally - but I can change the .NET documentation more directly, so I'll do that to start with :)
