### ISSUE TITLE
Cloud translation Google.Apis.Translate.v2 fails for short texts... "The Uri string is too long"

### ISSUE THREAD

**Issue by ivankrsul** [googleapis/google-cloud-dotnet#3018]
I am trying to get Translate to work for relatively short texts that are not based on latin alphabets... and in some cases the API behaves strangely. 

I am using .Net Framework 4.6.1 - and Google.Apis.Translate.v2 V 1.38.2.875.  The c#code I use is really simple: 

`            string text = File.ReadAllText(@"prikaz_o_polojenii_88Long.txt");
            TranslationClient client = TranslationClient.Create();
            var response = client.TranslateText(text, "en", "uz", TranslationModel.ServiceDefault);
            outputTtextBox.Text = response.TranslatedText;
`
and when I execute this I get the following exception:

`System.UriFormatException
  HResult=0x80131537
  Message=Invalid URI: The Uri string is too long.
  Source=System
  StackTrace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Google.Apis.Requests.RequestBuilder.UriJoin(Uri baseUri, String path)
   at Google.Apis.Requests.RequestBuilder.BuildUri()
   at Google.Apis.Requests.RequestBuilder.CreateRequest()
   at Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at Google.Cloud.Translation.V2.TranslationClientImpl.TranslateText(IEnumerable`1 textItems, String targetLanguage, String sourceLanguage, Nullable`1 model)
   at Google.Cloud.Translation.V2.TranslationClient.TranslateText(String text, String targetLanguage, String sourceLanguage, Nullable`1 model)
   at OCRTranslatePilot.Form1.button1_Click(Object sender, EventArgs e) in C:\Development\tax-diamond-ocr-translate-pilot\OCRTranslatePilot\OCRTranslatePilot\Form1.cs:line 555
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at OCRTranslatePilot.Program.Main() in C:\Development\tax-diamond-ocr-translate-pilot\OCRTranslatePilot\OCRTranslatePilot\Program.cs:line 19`

Whenever I do this with Spanish, German or French I have no issue, but non latin alphabets are complicated.  

When I feed the same code a Chinese file, I get another exception:

`Google.GoogleApiException
  HResult=0x80131500
  Message=Google.Apis.Requests.RequestError
Invalid Value [400]
Errors [
	Message[Invalid Value] Location[ - ] Reason[invalid] Domain[global]
]
  Source=Google.Apis
  StackTrace:
   at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at Google.Cloud.Translation.V2.TranslationClientImpl.TranslateText(IEnumerable`1 textItems, String targetLanguage, String sourceLanguage, Nullable`1 model)
   at Google.Cloud.Translation.V2.TranslationClient.TranslateText(String text, String targetLanguage, String sourceLanguage, Nullable`1 model)
   at OCRTranslatePilot.Form1.button2_Click(Object sender, EventArgs e) in C:\Development\tax-diamond-ocr-translate-pilot\OCRTranslatePilot\OCRTranslatePilot\Form1.cs:line 563
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at OCRTranslatePilot.Program.Main() in C:\Development\tax-diamond-ocr-translate-pilot\OCRTranslatePilot\OCRTranslatePilot\Program.cs:line 19`
 
So it seems that the Google API Google.Apis.Translate.v2 for .NET have poor support for non-latin languages... 

or I am doing something terribly wrong.  Please let me know if this is something that can be fixed on my end. 

Attached are the texts I used to test the AIP.

[Chinese.txt](https://github.com/googleapis/google-cloud-dotnet/files/3082337/Chinese.txt)

[prikaz_o_polojenii_88Long.txt](https://github.com/googleapis/google-cloud-dotnet/files/3082325/prikaz_o_polojenii_88Long.txt)

Ivan

**Comment by jskeet** [comment]
Could I ask which version of Google.Cloud.Translate.V1 you're using? The same problem was reported by another user recently, but it's fixed in version 1.2.0-beta01. If that's not the version you're using, could you give that a try please?

**Comment by ivankrsul** [comment]
I am using Google.Apis.Translate.v2 V 1.38.2.875.  

I think that the issue I am having has something to do with the fact that the text has new lines inside... and since the API passes the text in the URI string... everything breaks.  I figured that the API would URI encode the string to pass it to the web service...

Best regards

Ivan

**Comment by jskeet** [comment]
The code you quoted (using `TranslationClient` rather than just `TranslateService`) is using Google.Cloud.Translation.V2 - which wraps Google.Apis.Translate.v2. Please tell me the version of Google.Cloud.Translation.V2 that you're using.

**Comment by ivankrsul** [comment]
Sorry.  I was using Google.Apis.Translate.v2 directly.    Will try Google.Cloud.Translation.V2 and report shortly. 

Thanks!!!

Ivan

**Comment by jskeet** [comment]
> Sorry. I was using Google.Apis.Translate.v2 directly

The code you quoted in the first comment is *not* using it directly though. That's code using Google.Cloud.Translation.V2. Is that not your code?

**Comment by ivankrsul** [comment]
Yes.  I am sorry.  Its getting confusing with all the libraries I have installed  I am using V1.1.0 of Google.Cloud.Translation.V2.  

I will try to install V1.2.0-beta01 - will take a little while since I have to figure out how to get and install that version... my NuGet package manager does not list it   :) 

Ivan

**Comment by jskeet** [comment]
>  my NuGet package manager does not list it :)

You probably haven't got the box for including prereleases checked.

**Comment by ivankrsul** [comment]
Tried it... seems to work with V1.2.0-beta01!   Thanks a million and I am worry I wasted some of your precious time.

Ivan

**Comment by jskeet** [comment]
Not a problem at all - that's what I'm here for :)
