### ISSUE TITLE
Struct usage in Firestore Read/Write operations

### ISSUE THREAD

**Issue by DenSmoke** [googleapis/google-cloud-dotnet#3219]
I was trying to call `Transaction.Set` with `documentData` as `struct` object but got error:

```
System.InvalidOperationException: Type TechWiz.Lib.Core.Data.BroadcastMessage has no parameterless constructor
       at Google.Api.Gax.GaxPreconditions.CheckState[T](Boolean condition, String format, T arg0)
       at Google.Cloud.Firestore.Converters.AttributedTypeConverter..ctor(Type targetType, FirestoreDataAttribute attribute)
       at Google.Cloud.Firestore.Converters.AttributedTypeConverter.ForType(Type targetType)
       at Google.Cloud.Firestore.Converters.ConverterCache.CreateConverter(Type targetType)
       at Google.Cloud.Firestore.Converters.ConverterCache.<>c.<GetConverter>b__1_0(Type t)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at Google.Cloud.Firestore.Converters.ConverterCache.GetConverter(Type targetType)
       at Google.Cloud.Firestore.ValueSerializer.SerializeMap(Object value)
       at Google.Cloud.Firestore.WriteBatch.Set(DocumentReference documentReference, Object documentData, SetOptions options)
       at Google.Cloud.Firestore.Transaction.Set(DocumentReference documentReference, Object documentData, SetOptions options)
```

Is it a feature or bug? Error message is confusing

**Comment by jskeet** [comment]
Hmm. I suspect this is because as far as reflection is concerned, structs don't have parameterless constructors. (At least, typically - you can create one in IL, but life starts getting odd then.)

I don't think I've tried using a custom mutable value type in Firestore - I'd typically avoid using those in the first place, to be honest. Note that even if I can get it to work, the struct *will* be boxed during serialization and deserialization, so in those terms it won't help memory usage.

I'll look into fixing this - but unless it drops out nicely, I'm tempted not to support it (and to document that). Do you really *definitely* want a mutable value type, with all the oddities that come with that?

**Comment by DenSmoke** [comment]
> Note that even if I can get it to work, the struct will be boxed during serialization and deserialization, so in those terms it won't help memory usage.

I thought this optimization will reduce memory usage and GC load but now it is not obvious that it will help. But anyway I think struct must be supported because I'm sure there are some cases when it would be usefull.

Another approach is just forbid passing `struct` to any methods so anyone will be warned

**Comment by jskeet** [comment]
> I thought this optimization will reduce memory usage and GC load but now it is not obvious that it will help. 

It might help for use *elsewhere* in your code - but not in the Firestore serialization and deserialization steps.

> Another approach is just forbid passing struct to any methods so anyone will be warned

Except that a lot of the methods *would* work for some types, e.g. `int` or `Timestamp`. As I say, I'll have a look at how simple it is to implement.

**Comment by jskeet** [comment]
One point to note: this *is* already supported via a custom converter. See [this test code](https://github.com/googleapis/google-cloud-dotnet/blob/fa6f2acd6967a71da21c39198931bda246a4796a/apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/SerializationTestData.cs#L432) for an example. So even if it turns out to be infeasibly tricky with *just* attributes, there's a way forward for you.

**Comment by jskeet** [comment]
This is now in the master branch, but not released as a package. Please let me know if you need it urgently, otherwise I'll wait until I'd naturally be doing another release.
(Until then you could use a custom converter, of course.)

**Comment by DenSmoke** [comment]
It can wait until another release. Big thanks for fix
