### ISSUE TITLE
The type initializer for 'Google.Cloud.Firestore.V1.Firestore' threw an exception.

### ISSUE THREAD

**Issue by exgonline** [googleapis/google-cloud-dotnet#3408]
Hi, All of a sudden my .net core app is reporting the following issue when try to use Google.Cloud.Firestore.V1.Firestore.

All has been working fine until now! I am using .net core 2.25

System.TypeInitializationException: The type initializer for 'Google.Cloud.Firestore.V1.Firestore' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Google.Cloud.Firestore.V1.Document' threw an exception. ---> System.MissingMethodException: Method not found: 'Google.Protobuf.FieldCodec`1<System.String> Google.Protobuf.FieldCodec.ForString(UInt32)'.
   at Google.Cloud.Firestore.V1.Document..cctor()
   --- End of inner exception stack trace ---
   at Google.Cloud.Firestore.V1.Document.get_Parser()
   at Google.Cloud.Firestore.V1.Firestore..cctor()
   --- End of inner exception stack trace ---
   at Google.Cloud.Firestore.V1.Firestore.FirestoreClient.RunQuery(RunQueryRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiServerStreamingCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Cloud.Firestore.V1.FirestoreClientImpl.RunQuery(RunQueryRequest request, CallSettings callSettings)
   at Google.Cloud.Firestore.Query.<>c__DisplayClass54_0.<StreamResponsesAsync>b__0()
   at System.Linq.AsyncEnumerable.AnonymousAsyncEnumerable`1.GetEnumerator() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Create.cs:line 74
   at System.Linq.AsyncEnumerable.ForEachAsync_[TSource](IAsyncEnumerable`1 source, Action`2 action, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\ForEach.cs:line 139
   at Google.Cloud.Firestore.Query.GetSnapshotAsync(ByteString transactionId, CancellationToken cancellationToken)

**Comment by jskeet** [comment]
Please could you list your exact dependencies and their versions? There was a bug in Google.Protobuf 3.9.0, but we delisted that version, so I'd be surprised if you had a dependency on it now.

**Comment by exgonline** [comment]
Hi, I have installed Google Protobuf 3.9.1 from Nuget and the issue is fixed. I am using Cloud Firestore 1.1.0, .net core 2.2.6

Kind Regards and thanks for the reply.

**Comment by jskeet** [comment]
Okay, I'm glad it's fixed. It's not clear how you ended up on 3.9.0 (which I suspect you did somehow). Note that Firestore is only at version 1.0.0, so you can't be using 1.1.0 of it... it might be worth checking your dependencies and their versions very carefully.

**Comment by exgonline** [comment]
Hi I meant v1.0.0 of Firestore, typing issue this end sorry! Thanks for your help again
