### ISSUE TITLE
Dialogflow Client Library: Getting metadata from plugin failed with error: Exception occurred in metadata credentials plugin

### ISSUE THREAD

**Issue by MAOstrander** [googleapis/google-cloud-dotnet#4202]
Starting a few days ago a working project started experiencing intermittent issues with connecting to Dialogflow. I tried contacting their support, but they suggested I open an issue here instead.
It's quite simple that we're trying to use the C# library with a service account to make DetectIntent calls or use Events to trigger specific intents. 
Most of the time it works but lately we've seen a huge uptick in an error "Getting metadata from plugin failed with error: Exception occurred in metadata credentials plugin."
I'm sorry I don't have more specific details about how to reproduce, but it isn't something I've been able to reproduce locally, it's just happening once I've deployed it. (The credentials file is there and hasn't changed.)

#### Environment details

  - OS: Microsoft Windows 10 Enterprise LTSC
  - .NET version: 2.2.6
  - Package name and version: Google.Cloud.Dialogflow.V2 (1.0.0-beta02)

#### Steps to reproduce

1. Create a DetectIntentRequest using EventInput as the QueryInput.Event
2. Use SessionsClient.DetectIntent to try and detect the intent or event.
3. Most of the time it succeeds, sometimes it fails

Stacktrace looks like this:
```
2020-01-28 09:39:58,245 ERROR MyChatbot     - at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
at Google.Cloud.Dialogflow.V2.Sessions.SessionsClient.DetectIntent(DetectIntentRequest request, CallOptions options)
at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
at AIChatbot.Services.DialogflowService.DetectIntent(DetectIntentRequest request)
```

**Comment by jskeet** [comment]
Closing this as stale - if the problem still exists, please post a comment with more information as requested by Amanda.
