### ISSUE TITLE
When running on a google cloud compute instance, writing fails when using service account json file.

### ISSUE THREAD

**Issue by jamesrusso** [googleapis/google-cloud-dotnet#4519]
#### Environment details

  - OS: Windows
  - .NET version: 4.7.2
  - Package name and version: GoogleCloud.Logging.NLog v2.2.0, Google.Cloud.Logging.V2 v2.3.0

#### Steps to reproduce

  1. Create a simple project with a local service account with permissions to write to logs and run it on a local machine and it works fine. 

  2. Copy this project to a google cloud instance in a separate project and run it, and the logging will fail with permission denied.

Exception when running on cloud VM.

```
2020-03-05 11:53:28.5189 Error GoogleStackdriver(Name=google-cloud): Failed to write LogEntry Exception: System.AggregateException: One or more errors occurred. ---> Grpc.Core.RpcException: Status(StatusCode=PermissionDenied, Detail="The caller does not have permission")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext() in T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ApiCallRetryExtensions.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Logging.NLog.GoogleStackdriverTarget.<WriteLogEntriesBegin>d__27.MoveNext() in T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Logging.NLog\Google.Cloud.Logging.NLog\GoogleStackdriverTarget.cs:line 433
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Grpc.Core.RpcException: Status(StatusCode=PermissionDenied, Detail="The caller does not have permission")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext() in T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ApiCallRetryExtensions.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Logging.NLog.GoogleStackdriverTarget.<WriteLogEntriesBegin>d__27.MoveNext() in T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Logging.NLog\Google.Cloud.Logging.NLog\GoogleStackdriverTarget.cs:line 433<---
```

```
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace TestLogging
{
    class Program
    {

        static void Main(string[] args)
        {
            Logger logger = LogManager.GetLogger("foo");
            logger.Info("Program started");
        }
             
    }
}

```

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogToConsole="true"
      internalLogLevel="Info" internalLogFile="c:\temp\nlog-internal.log">

  <extensions>
    <add assembly="Google.Cloud.Logging.NLog" />
  </extensions>
  
  <targets>
    <target xsi:type="Console" name="console"
            layout="${longdate} ${uppercase:${level}} ${logger}: ${message} ${exception:format=ToString}" />
      <target name="stackdriver" type="GoogleStackdriver" projectId="<PROJECT_NAME>" logId="test-logging" credentialFile="credentials.json" />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="console,stackdriver"/>
  </rules>
</nlog>

````

Overview: 

I have an application that service account from one project. It is running on another project in a google cloud computing VM.  When running this from my local workstation pointing to a credentials.json service account, the logging works fine. However, when I copy this same simple project to the google cloud VM, it fails with permission denied. The service account has Project Owner permission. 

When turning on trace logging, I see the credential file contents in the internal nlog. So I know it's loading the credentials just fine. I suspect there is some magic happening with the google cloud instance service account and project overriding what is specified in the json credentials file. Since they are on different projects that might the issue, but I would expect when specifying the json service account would allow the logging to happen anywhere even on a google cloud vm in another project.

**Comment by jskeet** [comment]
Amanda, are you okay to dig into this a bit tomorrow?

**Comment by jamesrusso** [comment]
I'll work on a quick visual studio project to demo. I also plan to try it with a VM on the same project and see if that makes a difference, for some reason I feel like it will work when on same project? Just a hunch though.

**Comment by jamesrusso** [comment]
Here is just a simple project to save you the work of putting somethign together. 

Drop in a credentials.json service account file, edit the project name and logging target in the nlog.config and run it. 

https://github.com/jamesrusso/google-logging-nlog-issue-google-cloud-dotnet-issue-4519

I did confirm running this on a compute instance on the target project does work. So, the issue is running this on a compute instance on a separate project. I tested this with a fresh instance in the same project where the logs are supposed to be going.

Ex: Project A is running a compute instance that runs this code with a service account giving access to the logging facility on Project B. When running the code on the computer instance on Project A it will not work to log the data to Project B. However, when running on the same project it does seem to work ok. So, I somehow suspect that the project name is getting overridden somewhere down in the authentication code? I don't know enough about gsutil/gcloud to determine how this is happening. 

If I can assist further in tracking this done, please let me know. Thanks for your help.

**Comment by amanda-tarafa** [comment]
Yes I'll take a look, thanks for the sample project @jamesrusso

**Comment by amanda-tarafa** [comment]
#4520 Should fix this.
Thanks for reporting.

**Comment by jamesrusso** [comment]
You are a rockstar! Thanks @amanda-tarafa
