### ISSUE TITLE
[TextToSpeech] doesn't work without assembly redirection.

### ISSUE THREAD

**Issue by chinux23** [googleapis/google-cloud-dotnet#5042]
- OS: Window 10
  - .NET version: 4.7.2
  - Package name and version: Google Cloud TextToSpeech V1

#### Steps to reproduce
  0. Set up a fresh new Visual Studio Project.
  1. Follow Google Cloud TextToSpeech [tutorial](https://cloud.google.com/text-to-speech/docs/quickstart-client-libraries).
  2. use NuGet to install required package: for example Google.Cloud.TextToSpeech V1. All dependencies will be installed as well.
  2. Build the solution, this creates a Google TextToSpeech Console App (quickstart.exe, or whatever your VS project name is ).
  3. Now, go to the generated binary folder. Delete XML configuration for the newly created app. (If it's quickstart.exe, then remove QuickStart.exe.config). What this config does is to allow Assembly redirection.
  4. Rerun the console app (i.e. quickstart.exe), an error will occur.

The first exception is this

```
C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\SynthesizeSpeech>SpeechSynthesizerTest.exe

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Google.Apis.Core, Version=1.44.1.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Google.Api.Gax.Grpc.ChannelPool.CreateChannelCredentialsUncached()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions(Task task) in T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax\TaskExtensions.cs:line 51
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions) in T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ChannelPool.cs:line 97
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker() in T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ClientBuilderBase.cs:line 280
   at Google.Cloud.TextToSpeech.V1.TextToSpeechClientBuilder.BuildImpl() in T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.TextToSpeech.V1\Google.Cloud.TextToSpeech.V1\TextToSpeechClient.g.cs:line 119
   at Google.Cloud.TextToSpeech.V1.TextToSpeechClientBuilder.Build() in T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.TextToSpeech.V1\Google.Cloud.TextToSpeech.V1\TextToSpeechClient.g.cs:line 103
   at QuickStart.Main(String[] args)
```

Fine, Let's use NuGet to change Google.Apis.Core and related library to 1.44.1.0.

Recompile the code, (and remove the configuration file again, i.e. quickstart.exe, since rebuilding will create a new configuration file).

Now rerun the code gives this exception:

```
C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\SynthesizeSpeech>SpeechSynthesizerTest.exe

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Google.Apis.Auth, Version=1.21.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Google.Api.Gax.Grpc.ChannelPool.<CreateChannelCredentialsUncached>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Google.Api.Gax.Grpc.ChannelPool.CreateChannelCredentialsUncached()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions(Task task) in T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax\TaskExtensions.cs:line 51
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions) in T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ChannelPool.cs:line 97
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker() in T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ClientBuilderBase.cs:line 280
   at Google.Cloud.TextToSpeech.V1.TextToSpeechClientBuilder.BuildImpl() in T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.TextToSpeech.V1\Google.Cloud.TextToSpeech.V1\TextToSpeechClient.g.cs:line 119
   at Google.Cloud.TextToSpeech.V1.TextToSpeechClientBuilder.Build() in T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.TextToSpeech.V1\Google.Cloud.TextToSpeech.V1\TextToSpeechClient.g.cs:line 103
   at QuickStart.Main(String[] args)

C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\SynthesizeSpeech>
```

My understanding is that Google.Api.Gax.Grpc.ChannelPool depends on Google.Apis.Auth 1.21.0.0. However, I can no longer use NuGet to select Google.Apis.Auth 1.21.0.0 because Google.Api.Gax 1.0.0 has a constraint.

```
Attempting to resolve dependencies for package 'Google.Apis.Auth.1.21.0' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Google.Apis.Auth 1.44.1'
Unable to resolve dependencies. 'Google.Apis.Auth 1.21.0' is not compatible with 'Google.Api.Gax 1.0.0 constraint: Google.Apis.Auth (>= 1.24.0)'.
```

I want to add Google.Cloud.TextToSpeech to an application that doesn't have "App Config File" (the quickstart.exe.config in this case). But I can't because it will not be able to do assembly redirection and gives out above exception.

Is there a way to get around this?

Thanks!

**Comment by jskeet** [comment]
> Is there a way to get around this?

No, I'm afraid not. Assembly binding redirects are just a fact of life in modern .NET applications which use multiple packages - it's infeasible to keep every package involved in absolute lock-step. I would suggest that instead of trying to work out how to avoid assembly binding redirects, you focus on overcoming whatever problems they're giving you. (You haven't explained *why* you don't want there to be an app config file.)

**Comment by chinux23** [comment]
I'm working on a mod that changes a game I don't own using [Harmony lib](https://github.com/pardeike/Harmony)

I didn't find any app.config in the application's binary folder. I assume this means that the application doesn't use binary redirection? Is this correct statement?

**Comment by jskeet** [comment]
Well can you *create* that file? Just because it doesn't exist now doesn't mean you *can't* use binding redirects. But you may well want to teach out to the Harmony authors for support. I'm afraid it's not really going to be feasible to try to line up all the dependencies without redirects.

**Comment by jskeet** [comment]
I'm going to close this issue now as I don't believe there's any further work to be done within this repository, but we can still discuss possible solutions in comments. (I do think that you'll get further asking about redirects within Harmony lib itself though.)

**Comment by chinux23** [comment]
Thanks. That's fine with me. I did try to add the config file manually, unfortunately the binary doesn't seem to use it. Anyways, thanks for the help and investigation, although I found it a bit strange that gcloud client library itself has different version dependencies.

**Comment by jskeet** [comment]
> I found it a bit strange that gcloud client library itself has different version dependencies.

The set of dependencies is very complicated. I suspect it would be just about feasible (but still unpleasant) to avoid needing anything if we didn't need to depend on Grpc.Auth, but we do... and that depends on Google.Apis.Auth, as do the Google Cloud libraries (indirectly). That's why the version mismatch occurs, I believe. Basically by the time you've got about 10 libraries involved, all with different release cycles (for good reasons) we really need to be able to depend on SemVer handling just working.
