### ISSUE TITLE
Synthesis failed for Google.Cloud.Asset.V1

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-cloud-dotnet#5108]
Hello! Autosynth couldn't regenerate Google.Cloud.Asset.V1. :broken_heart:

Here's the output from running `synth.py`:

```
Traceback (most recent call last):
  File "/usr/local/google/home/rennie/.vscode/extensions/ms-python.python-2020.5.86398/pythonFiles/lib/python/debugpy/no_wheels/debugpy/_vendored/pydevd/pydevd.py", line 3148, in <module>
    main()
  File "/usr/local/google/home/rennie/.vscode/extensions/ms-python.python-2020.5.86398/pythonFiles/lib/python/debugpy/no_wheels/debugpy/_vendored/pydevd/pydevd.py", line 3141, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/local/google/home/rennie/.vscode/extensions/ms-python.python-2020.5.86398/pythonFiles/lib/python/debugpy/no_wheels/debugpy/_vendored/pydevd/pydevd.py", line 2266, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/usr/local/google/home/rennie/.vscode/extensions/ms-python.python-2020.5.86398/pythonFiles/lib/python/debugpy/no_wheels/debugpy/_vendored/pydevd/pydevd.py", line 2290, in _exec
    runpy._run_module_as_main(module_name, alter_argv=False)
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/google/home/rennie/gitrepos/synthtool/autosynth/synth.py", line 644, in <module>
    main()
  File "/usr/local/google/home/rennie/gitrepos/synthtool/autosynth/synth.py", line 498, in main
    return _inner_main(temp_dir)
  File "/usr/local/google/home/rennie/gitrepos/synthtool/autosynth/synth.py", line 542, in _inner_main
    args.logs_file_dir or pathlib.Path(os.path.realpath("./logs")) / args.repository
AttributeError: 'Namespace' object has no attribute 'logs_file_dir'

```

Google internal developers can see the full log [here](http://sponge2/results/invocations/None/targets/github%2Fsynthtool;config=default/tests;query=google-cloud-dotnet;failed=false).

**Comment by SurferJeffAtGoogle** [comment]
Autosynth is still having trouble generating Google.Cloud.Asset.V1. :sob:

Here's the output from running `synth.py`:

```
usage: synth.py [-h] [--github-user GITHUB_USER] [--github-email GITHUB_EMAIL]
                [--github-token GITHUB_TOKEN] --repository REPOSITORY
                [--synth-path SYNTH_PATH] [--metadata-path METADATA_PATH]
                [--logs-file-dir LOGS_FILE_DIR] [--deprecated-execution]
                [--branch-suffix BRANCH_SUFFIX] [--pr-title PR_TITLE]
                ...
synth.py: error: unrecognized arguments: --log-file-dir

```

Google internal developers can see the full log [here](http://sponge2/results/invocations/None/targets/github%2Fsynthtool;config=default/tests;query=google-cloud-dotnet;failed=false).
