### ISSUE TITLE
You have passed an invalid argument to the service (argument=max_messages).

### ISSUE THREAD

**Issue by KingR1** [googleapis/google-cloud-dotnet#5378]
I'm using Google.Cloud.PubSub.V1 (v1.0)

I have peace of code where I try to pull:
`var subscriberClient = await SubscriberServiceApiClient.CreateAsync().ConfigureAwait(false);
`
`var pullResponse = await subscriberClient.PullAsync(subscriptionName, true, maxMessages).ConfigureAwait(false);`

When an application calls method which uses that part of code, I receive a warning:

> "Grpc.Core.RpcException: Status(StatusCode=InvalidArgument, Detail="You have passed an invalid argument to the service (argument=max_messages).")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyApp.Service.Infrastructure.MessageBroker.MessageBrokerService.<PullManyAsync>d__10.MoveNext() in D:\projects\my-services\Services\Infrastructure\MessageBroker\Service\MessageBrokerService.cs:line 121" 

Why is that? Is there some version mismatch? According to documentation, I can pass number of messages.

**Comment by jskeet** [comment]
What is the value of your `maxMessages` variable? Given that you're using `SubscriberServiceApiClient`, there's no handwritten code involved here - you're basically just sending an RPC straight to the server. The documentation states that it has to be "a positive integer" but that's the only listed requirement... if you could let us know what the value of `maxMessages` is (ideally logged just because the RPC) that would really help.

**Comment by KingR1** [comment]
@jskeet Hi, Thx for the quick reply. The number should be positive or 1... but let me check if it can be 0 as it is calculated variable.

**Comment by KingR1** [comment]
@jskeet yes, looks like in some cases 0 was passed as `maxMessages` value. 
Thx for help.
