### ISSUE TITLE
SecretManagerServiceClient.Create() crash in .NET 5.0 Docker image

### ISSUE THREAD

**Issue by iocheredko** [googleapis/google-cloud-dotnet#5629]
The **SecretManagerServiceClient.Create()** execution is crashing in the official .NET 5 Docker image (mcr.microsoft.com/dotnet/aspnet:5.0 from [https://hub.docker.com/_/microsoft-dotnet-aspnet](https://hub.docker.com/_/microsoft-dotnet-aspnet))
The stack trace is:
```
System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory
         at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags)
         at Grpc.Core.Internal.UnmanagedLibrary.LoadLibraryPosix(Func`3 dlopenFunc, Func`1 dlerrorFunc, String libraryPath, String& errorMsg)
         at Grpc.Core.Internal.UnmanagedLibrary.PlatformSpecificLoadLibrary(String libraryPath, String& errorMsg)
         at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
         at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
         at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
         at Grpc.Core.Internal.NativeExtension..ctor()
         at Grpc.Core.Internal.NativeExtension.Get()
         at Grpc.Core.Internal.NativeMethods.Get()
         at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
         at Grpc.Core.GrpcEnvironment..ctor()
         at Grpc.Core.GrpcEnvironment.AddRef()
         at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
         at Google.Api.Gax.Grpc.GrpcCore.GrpcCoreAdapter.CreateChannelImpl(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
         at Google.Api.Gax.Grpc.GrpcAdapter.CreateChannel(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
         at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions, ChannelCredentials credentials)
         at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions)
         at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker()
         at Google.Cloud.SecretManager.V1.SecretManagerServiceClientBuilder.BuildImpl()
         at Google.Cloud.SecretManager.V1.SecretManagerServiceClientBuilder.Build()
         at Google.Cloud.SecretManager.V1.SecretManagerServiceClient.Create()
```

As a workaround I was able to fix that by adding this line to the Dockerfile:
```
RUN apt-get install -y libc6-dev
```

The error does not appear in the .NET Core 3.1 Docker image.

**Comment by jskeet** [comment]
This is an issue with Grpc.core on .NET 5.0, which will be fixed in a later version of Grpc.Core. See https://github.com/grpc/grpc/issues/24153 for more details.

I'll close this issue now as there's nothing we can do at a client library level, so there's no change required in this repository. Once an updated version of Grpc.Core is available, we'll of course update our dependencies for future library releases, but you'll also be able to simply add an explicit dependency on the new version of Grpc.Core as well.

**Comment by EatonZ** [comment]
@jskeet When can you update the version? I am getting this crash too, and NuGet in VS isn't showing any updates for anything.

**Comment by jskeet** [comment]
@EatonZ: I'm not on the gRPC team. The only thing *I* can update is the dependency on Grpc.Core, which I will do - but I'm not intending to then release 50+ packages imminently.

It looks like Grpc.Core 2.34.0 has been released now, so you should be able to add a dependency to that yourself, which should solve the problem. I don't know why VS isn't showing you any updates, but adding a direct dependency on Grpc.Core version 2.34.0 should be fine.

**Comment by EatonZ** [comment]
> I'm not on the gRPC team. The only thing I can update is the dependency on Grpc.Core, which I will do

Yes, that is what I was referring to 🙂

> I don't know why VS isn't showing you any updates

Probably because I don't have it directly installed into my project. Only Google libraries reference it.

> adding a direct dependency on Grpc.Core version 2.34.0 should be fine.

Yes, this has fixed it. Thank you.

**Comment by jskeet** [comment]
Looks like Grpc.Core 2.34.0 has issues in terms of strong-naming - if it's working for you, that's great... if you run into problems, follow https://github.com/grpc/grpc/issues/24935 for progress.

**Comment by EatonZ** [comment]
@jskeet Fortunately .NET Core doesn't seem to have problems with that anymore.🙂
