### ISSUE TITLE
Error while creating Projects

### ISSUE THREAD

**Issue by thegreedychoice** [googleapis/google-cloud-dotnet#7617]
#### Environment details

  - OS: Mac OS
  - .NET version: .NET 6 (Azure Functions Isolated Model)
  - Package name and version: Google.Cloud.ResourceManager.V3

#### Steps to reproduce

  1. I'm using the package in my Azure Functions project and basically calling the CreateFunction() project. 
  2. https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3.Snippets/ProjectsClientSnippets.g.cs#L643
  2. I'm able to successfully create the project but when its tries to poll the response, I get error as described below. 
   **Operation<Project, CreateProjectMetadata> completedResponse = response.PollUntilCompleted();**

Source Code

            // Create client
            projectsClient = await ProjectsClient.CreateAsync();

            // Make the request
            Operation<Project, CreateProjectMetadata> response = await projectsClient.CreateProjectAsync(project);

            // Poll until the returned long-running operation is complete
            Operation<Project, CreateProjectMetadata> completedResponse = await response.PollUntilCompletedAsync();
            // Retrieve the operation result

Error:
System.Private.CoreLib: Exception while executing function: Functions.CreateProjectHttpTrigger. System.Private.CoreLib: Result: Failure

Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode="Unimplemented", Detail="Received http2 header with status: 404", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1638918155.841700000","description":"Received http2 :status header with non-200 OK status","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/http/client/http_client_filter.cc","file_line":133,"grpc_message":"Received http2 header with status: 404","grpc_status":12,"value":"404"}"))

---> Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Received http2 header with status: 404", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1638918155.841700000","description":"Received http2 :status header with non-200 OK status","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/http/client/http_client_filter.cc","file_line":133,"grpc_message":"Received http2 header with status: 404","grpc_status":12,"value":"404"}")

at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)

at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)

 at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)

at Grpc.Core.Interceptors.InterceptingCallInvoker.b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)

at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext2 context, BlockingUnaryCallContinuation2 continuation)

 at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)

at Grpc.Core.Interceptors.InterceptingCallInvoker.b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)

at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext2 context, BlockingUnaryCallContinuation2 continuation)

 at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)

at Google.LongRunning.Operations.OperationsClient.GetOperation(GetOperationRequest request, CallOptions options)

at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)

at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.b__0(TRequest request, CallSettings callSettings)

at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass10_0.b__1(TRequest req, CallSettings cs)

 at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)

 at Google.LongRunning.OperationsClientImpl.GetOperation(GetOperationRequest request, CallSettings callSettings)

at Google.LongRunning.OperationsClient.GetOperation(String name, CallSettings callSettings)

at Google.LongRunning.Operation`2.PollOnceFromName(String name, OperationsClient client, CallSettings callSettings)

 at Google.Cloud.ResourceManager.V3.ProjectsClient.PollOnceCreateProject(String operationName, CallSettings callSettings)

at team.Automation.Gcp.FunctionApp.Clients.GcpResourceManagerClient.CreateProject(Project project) in /Users/xxsh/Desktop/src/repos/team/team.automation.gcp.api/team.Automation.Gcp/team.Automation.Gcp.FunctionApp/Clients/GcpResourceManagerClient.cs:line 40

 at team.Automation.Gcp.FunctionApp.Api.CreateProjectHttpTrigger.ProcessCreateProject(IncomingRequestEntity requestData, String requestId, ILogger _logger) in /Users/xxsh/Desktop/src/repos/team/team.automation.gcp.api/team.Automation.Gcp/team.Automation.Gcp.FunctionApp/Apis/CreateProjectHttpTrigger.cs:line 90

Automation.Gcp.FunctionApp.Api.CreateProjectHttpTrigger.Run(HttpRequestData req) in /Users/xxsh/Desktop/src/repos/automation.gcp.api/team.Automation.Gcp/team.Automation.Gcp.FunctionApp/Apis/CreateProjectHttpTrigger.cs:line 53

--- End of inner exception stack trace ---
Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jskeet** [comment]
Please could you try to run the same code from a simple console application? We've had issues with dependencies in Azure Functions in the past... I don't *think* that's the issue here, but a minimal example that can be run from a developer workstation would be really helpful for pinning things down.

**Comment by jskeet** [comment]
(Additionally, if you could let me know whether you're doing any other long-running operations with Cloud ResourceManager, and whether they face the same issues, that would be useful information.)

**Comment by thegreedychoice** [comment]
@jskeet  Yes, I still get the same following error when I run it in a .net console application:

"Status(StatusCode=\"Unimplemented\", Detail=\"Received http2 header with status: 404\", DebugException=\"Grpc.Core.Internal.CoreErrorDetailException: {\"created\":\"@1638981000.168336000\",\"description\":\"Received http2 :status header with non-200 OK status\",\"file\":\"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/http/client/http_client_filter.cc\",\"file_line\":133,\"grpc_message\":\"Received http2 header with status: 404\",\"grpc_status\":12,\"value\":\"404\"}\")"


Configuration:
OS: Mac OS
.Net Version - .net 6 (console app)


Code:

class Program
    {
        public static void Main(string[] args)
        {
            var environmentName = Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");


            // get the service account credential from environment
            GoogleCredential credential = GoogleCredential.GetApplicationDefault();

            ProjectsClient projectsClient = ProjectsClient.Create();

            Project project = new Project();
            project.ProjectId = "team-project-14";
            project.Parent = "folders/36867623499";

            // Project result = null;            
            // Make the request
            Operation<Project, CreateProjectMetadata> response = projectsClient.CreateProject(project);

            // Poll until the returned long-running operation is complete
            Operation<Project, CreateProjectMetadata> completedResponse = response.PollUntilCompleted();
      }
}

And no, I am not running any Long Running operations additionally. I'm only trying to create projects for now.

**Comment by jskeet** [comment]
Right, thanks for the extra detail. I'll see if I can reproduce it, and talk to the team internally about what's happening.

**Comment by jskeet** [comment]
I've now managed to reproduce this, and I'll look into what's going on. I have a *slight suspicion* which will be relatively hard to fix "properly" but hopefully relatively straightforward to work around with some sample code.

**Comment by jskeet** [comment]
I've discovered that client libraries for other languages are running into the same problem, and I've asked the Resource Manager team about it. Things may go quite for a little while during internal conversations, but I'll update this issue as soon as I can.

**Comment by thegreedychoice** [comment]
@jskeet  Thanks for the update. Would you know when can we expect the workaround to be implemented and the sample code? I have a tight deadline and I wanted to understand if I should replace SDK for REST APIs directly in my work for now.

**Comment by jskeet** [comment]
At the moment I don't know whether there *is* a feasible workaround - my "slight suspicion" was wrong. It's *possible* that there'll be a workaround, but right now I'm not hopeful. I think it would be safer to use the REST API right now, but if you can isolate the code so that you can switch it out easily later on, that would be ideal.

**Comment by thegreedychoice** [comment]
Okay, thanks for the update. I'll work with the API for now.

**Comment by jskeet** [comment]
Hi @thegreedychoice. Thanks very much for your patience. The API team has been working hard behind the scenes, and the existing library now works - at least, my repro now passes when it failed, and I have confidence that the underlying problem is fixed.

So you should now be able to come back to this library instead of the REST API, unless you've already written huge amounts of code with the REST API and don't want to switch back :)
