### ISSUE TITLE
Pub/Sub PublisherClient.CreateAsync() does not take credentials from clientCreationSettings into account if serviceEndpoint is set

### ISSUE THREAD

**Issue by murlex** [googleapis/google-cloud-dotnet#7968]
#### Environment details

  - OS: Windows 10
  - .NET version 5.0:
  - Package name and version: Google.Cloud.PubSub.V1; 2.7.0

#### Steps to reproduce
PublisherClient.PublishAsync() throws authentication exception because it does not take credentials passed in clientCreationSettings.Credentials into account if clientCreationSettings.ServiceEndpoint is set. It *does not throw* if I am not setting service endpoint.

Code example (throws exception):
```
var creds = GoogleCredential.FromJson(_jsonCredentials); // string contains normal service account credentials read from file
var clientCreationSettings = new PublisherClient.ClientCreationSettings(null, null, creds.ToChannelCredentials(), "us-east1-pubsub.googleapis.com:443");
var pubClient = await PublisherClient.CreateAsync(_currentTopic, clientCreationSettings, customSettings);
await pubClient.PublishAsync(orderKey, message); // THROWS EXCEPTION            

```
If use pass null instead of `"us-east1-pubsub.googleapis.com:443"` then no exception is thrown

**Comment by murlex** [comment]
Sure. My inference is based on the exception thrown. I am not sure of course what exactly going on behind the scene.
Here please the exception itself with stack trace. Thank you for fast response.
```
Grpc.Core.RpcException: Status(StatusCode="Unauthenticated", Detail="Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1644782110.249000000","description":"Error received from peer ipv4:142.250.185.202:443","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1067,"grpc_message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}")
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult()
   at Google.Cloud.PubSub.V1.Tasks.Extensions.<>c__DisplayClass5_0`1.<<ConfigureAwaitHideErrors>g__Inner|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult()
   at Google.Cloud.PubSub.V1.PublisherClientImpl.PublishAsync(PubsubMessage message)
   at ConsoleApp14.Program.Publish(String message, String times) in C:\Users\I540758\source\repos\ConsoleApp11\ConsoleApp11\Program.cs:line 127
 ```

**Comment by murlex** [comment]
Thanx a lot! I'll try it tomorrow and tell you if it works for me.

**Comment by murlex** [comment]
Yeah. The workaround works like charm. Thanx!

**Comment by jskeet** [comment]
Great - closing now, thanks.
