### ISSUE TITLE
Calls to Google.Cloud.Storage.V1.UploadObject start failing with message "a task was canceled"

### ISSUE THREAD

**Issue by feboz** [googleapis/google-cloud-dotnet#8197]
Maybe this is not the right place, but I'm roaming from days and I don't know where else I can ask for help.
I'm using Google Video Intelligence to process videos and Cloud Storage to upload files to be processed. I'm working in .Net, and using Google.Cloud.Storage.V1 (3.7.0) to handle requests to the Storage service. It was working fine until my app was runnig on local machine, now I deployed it on AWS and it started to failing on the Google.Cloud.Storage.V1.UploadObject method.
This is the code part:

```
public bool UploadBlob(string destFilename, string mimeType, Stream content)
{
   try
   {
      logger.LogInformation($"{DateTime.Now}: bucket name: {BucketName}");
      logger.LogInformation($"{DateTime.Now}: Uploading file in bucket {BucketName}");
      logger.LogInformation($"{DateTime.Now}: file data: {destFilename}, {mimeType}, content.Length}");
      var obj = StorageClient.UploadObject(BucketName, destFilename, mimeType, content);
   }
   catch (TaskCanceledException ex)
   {
     if (ex.CancellationToken.IsCancellationRequested)
     {
        logger.LogError($"{DateTime.Now}:IsCancellationRequested");
     }
     logger.LogError($"{DateTime.Now}:{ex.Message}");
     logger.LogError($"{DateTime.Now}:{ex.InnerException.Message}");
   }
   return true;
}
```
And this is the resulting logs with exception:
```
02/18/2022 13:55:59: bucket name: mmmanager2
02/18/2022 13:55:59: Uploading file in bucket mmmanager2
02/18/2022 13:55:59: file data: 3EDXNPHF3D2T058ICVIG.mp4, video, 79826367
02/18/2022 13:57:39:IsCancellationRequested
02/18/2022 13:57:39:A task was canceled.

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.

   at VideoAnnotationService.UploadBlob(String fileName, String destFilename, String mimeType, Stream content)

   at Workers.VideoWorker.<>c__DisplayClass15_0.<<UploadVideo>b__0>d.MoveNext() ...

--- End of stack trace from previous location where exception was thrown ---

   at VideoWorker.ProcessMultimedia() in ...

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)

   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I'm using default outbound rules so all the traffic is permitted so I don't think AWS platform could be an issue. 

At the moment I don't know what approach to use to debug this.

Any help is welcome.

Thank you.

**Comment by feboz** [comment]
Hi,
that's all exception message is, hope can help:
```
02/23/2022 14:22:37:ex: System.Threading.Tasks.TaskCanceledException: A task was canceled.

         at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.CheckFinalProgress()

         at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.Execute()

         at Google.Cloud.Storage.V1.StorageClientImpl.UploadObject(Object destination, Stream source, UploadObjectOptions options, IProgress`1 progress)

         at Google.Cloud.Storage.V1.StorageClientImpl.UploadObject(String bucket, String objectName, String contentType, Stream source, UploadObjectOptions options, IProgress`1 progress)

         at VideoAnnotationService.UploadBlob(String fileName, String destFilename, String mimeType, Stream content)

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.

   at VideoAnnotationService.UploadBlob(String fileName, String destFilename, String mimeType, Stream content)

   at MultimediaManagerService.Workers.VideoWorker.<>c__DisplayClass15_0.<<UploadVideo>b__0>d.MoveNext() in F:\Progetti\MultimediaManagerService\Workers\VideoWorker.cs:line 376

--- End of stack trace from previous location where exception was thrown ---

   at MultimediaManagerService.Workers.VideoWorker.ProcessMultimedia() in F:\Progetti\MultimediaManagerService\Workers\VideoWorker.cs:line 101

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)

   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
Thank you for the fast reply.
Fabio

**Comment by jskeet** [comment]
Right. So it sounds like it's timed out during the upload - it looks like a 100 second timeout. I'd certainly expect it to take a lot less time than that to upload 79MB.

Are you able to test whether it works for very small uploads? Also, please could you show how you're constructing the client, including anything you're doing for authentication?

(As an aside, the `NullReferenceException` is just because you're trying to log `ex.InnerException.Message`. That's nothing to do with the storage library. If you're logging the whole exception now, you can get rid of all the extra bits of logging.)

**Comment by feboz** [comment]
I tried with a video of just 869 KB, same results, then right now I noticed that a request to Google.Cloud.Translation.V2 has also the same problem. 
It could be a network problem from AWS, but other requests to external services are working.

**Comment by jskeet** [comment]
Again, please show how you're constructing the client and what you're doing for authentication. It's possible that it's actually the authentication request that's timing out.

**Comment by feboz** [comment]
Both codes added,
I succesfully received the access token substring and the same problem occurs while listing bucket objects.
Here's the exception log:
```
02/23/2022 18:52:45:ex: System.Threading.Tasks.TaskCanceledException: A task was canceled.

         at Google.Apis.Requests.ClientServiceRequest`1.Execute()

         at Google.Api.Gax.Rest.RestPagedEnumerable`3.AsRawResponses()+MoveNext()

         at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()

         at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)

         at VideoAnnotationService.UploadBlob(String fileName, String destFilename, String mimeType, Stream content)
```

**Comment by jskeet** [comment]
Okay, that's interesting. Assuming there aren't thousands of objects in your bucket (we can always try a different operation, of course), that suggests there's a problem accessing https://storage.googleapis.com

I've finished work for the day now, but I'll have a look tomorrow at putting together some sample code to make a similar request directly with `HttpClient`.

**Comment by feboz** [comment]
Ok,
actually the bucket is empty,
Thank you for your support!

**Comment by jskeet** [comment]
Right - if the bucket is empty, then it should still be entirely valid, and return quickly.

Before I get to it tomorrow, please could you let me know any interesting details of *how* you're deploying it on AWS? I don't know much about AWS but in GCP at least there are lots of different ways of deploying (VM, Cloud Run, GKE, Cloud Functions etc). I would imagine it's the same for AWS.

**Comment by feboz** [comment]
It is a .Net core service in a Docker Container running on an Ubuntu VM.

**Comment by jskeet** [comment]
Okay, here's some more code to test. Note that in the previous auth token test, we didn't have any scopes, so I believe it would actually have been creating a self-signed JWT - which means you may well find that fetching the auth token *does* fail here.

This code assumes you have somewhere you can execute an async method.

```csharp
using Google.Apis.Auth.OAuth2;
using Google.Apis.Storage.v1;
using System.Net.Http.Headers;

...

string bucketName = "...";

ITokenAccess cred = GoogleCredential.GetApplicationDefault()
    .CreateScoped(StorageService.Scope.CloudPlatform);

var token = await cred.GetAccessTokenForRequestAsync("https://storage.googleapis.com");
var httpClient = new HttpClient();
string uri = $"https://storage.googleapis.com/storage/v1/b/{bucketName}/o";
var request = new HttpRequestMessage
{
    RequestUri = new Uri(uri),
    Method = HttpMethod.Get,
    Headers =
    {
        Authorization = new AuthenticationHeaderValue("Bearer", token)
    }
};

var response = await httpClient.SendAsync(request);
logger.LogInformation("Status: {status}", response.StatusCode);
string text = await response.Content.ReadAsStringAsync();
logger.LogInformation("Response content: {content}", text);
```

**Comment by feboz** [comment]
Here's the resulting exception:
```
Unhandled exception. System.InvalidOperationException: The access token has expired and could not be refreshed. Errors: timeout, timeout, timeout

   at Google.Apis.Auth.OAuth2.TokenRefreshManager.RefreshTokenAsync()

   at Google.Apis.Auth.OAuth2.TokenRefreshManager.GetAccessTokenForRequestAsync(CancellationToken cancellationToken)

   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.GetAccessTokenForRequestAsync(String authUri, CancellationToken cancellationToken)

   at VideoAnnotationService.UploadBlobAsync(String fileName, String destFilename, String mimeType, Stream content)

   at MultimediaManagerService.Workers.VideoWorker.<>c__DisplayClass15_0.<<UploadVideo>b__0>d.MoveNext() in F:\MultimediaManagerService\Exprivia.ILab.Findustry.MultimediaManagerService\Workers\VideoWorker.cs:line 376
```

**Comment by jskeet** [comment]
Okay, so it looks like the problem *is* with auth after all.

Here's another bit of code to just check `HttpClient` interaction with the Google OAuth servers:

```csharp
var httpClient = new HttpClient();
var request = new HttpRequestMessage
{
    RequestUri = new Uri("https://accounts.google.com/o/oauth2/token"),
    Method = HttpMethod.Post,
    Content = new FormUrlEncodedContent(new[] { KeyValuePair.Create("key", "value")})
};
var response = await httpClient.SendAsync(request);
logger.LogInformation("Status: {status}", response.StatusCode);
string text = await response.Content.ReadAsStringAsync();
logger.LogInformation("Response content: {content}", text);
```

Obviously that's not actually going to get an access token - but hopefully it will at least show the response. (I'd expect a response of "BadRequest" with JSON showing an error of "unsupported_grant_type".)

**Comment by jskeet** [comment]
Another URL to try with the above code is https://oauth2.googleapis.com/token - apologies, I had misread our own code.

Additionally, please could you tell us what kind of credential you've got in your JSON file? I expect it's probably a service account credential, but it's worth checking.

**Comment by feboz** [comment]
Exeption with both Urls
```
 02/24/2022 11:04:10:ex: System.Threading.Tasks.TaskCanceledException: The operation was canceled.

         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(HttpRequestHeaders headers, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

         at VideoAnnotationService.UploadBlobAsync(String fileName, String destFilename, String mimeType, Stream content)
```
Yes it is a service account.

**Comment by jskeet** [comment]
Okay, so at this point the problem clearly isn't in the client libraries - you need to review your network configuration, firewalls etc. You originally wrote:

> I'm using default outbound rules so all the traffic is permitted so I don't think AWS platform could be an issue.

... but it really sounds like that *is* the problem. You might want to try connecting to some other URLs (e.g https://www.google.com, https://microsoft.com, https://wikipedia.org) to see if there's any pattern in what you can and can't reach.

**Comment by feboz** [comment]
Yes the problem occurs also for https://www.google.com/ and https://microsoft.com/, but it works with an external service making NLP.....quite strange!
I tried also with http instead of https, same results.
Fabio

**Comment by jskeet** [comment]
Okay - I'm afraid at this point I don't think I have any other information to offer, as the problem definitely isn't in the client libraries. Hopefully you'll be able to find AWS experts who can help with the networking side. I'll close the issue now, but best of luck resolving it. (And if you can resolve the networking and you *still* have problems with the libraries, do either add another comment here or create a new issue, of course.)

**Comment by feboz** [comment]
ok,
Thank you for your support!
Fabio
