### ISSUE TITLE
GoogleApiException: Error response is null

### ISSUE THREAD

**Issue by lukepuplett** [googleapis/google-cloud-dotnet#8211]
I have just encountered an exception with an error message that does not produce any Google search results. I am just testing my app for the first time after rewriting it to use Google Storage.

I don't expect a resolution, but rather I'm posting here so other people encountering the error can at least get a search result for it.

The issue was repeatable. Each time I performed the same action in my app, it caused the error. However, that code is used in other actions and works. That is to say my call to `GetBucketAsync()` works and then doesn't work, depending on what I do in my app. It also caused my debugger to crash on `GetBucketAsync()` and it felt like it crashed from just stopping on that line, not executing it but maybe I imagined that.

It's all a bit strange. I'll keep experimenting and update.

#### Environment details

  - OS: macOS 12.2.1
  - .NET version: 6.0.100
  - Package name and version: Google.Cloud.Storage.V1, Version=3.6.0.0

#### Steps to reproduce

  1. Use the `StorageClient.GetBucketAsync(...)` method
  2. Observe an error sometimes.

Stack trace is below.

The service storage has thrown an exception: Google.GoogleApiException: Error response is null
   at Google.Apis.Services.BaseClientService.DeserializeError(HttpResponseMessage response)
   at Google.Apis.Requests.ClientServiceRequest`1.ParseResponse(HttpResponseMessage response)
   at Google.Apis.Requests.ClientServiceRequest`1.ExecuteAsync(CancellationToken cancellationToken)
   at Google.Apis.Requests.ClientServiceRequest`1.ExecuteAsync()
   at AcmeCorp.Coyote.Data.GoogleBlobs.GoogleIndexedObjectStore`1.GetBlobHeadsAsync(OpContext op) in /Users/lukepuplett/Documents/Git/Coyote/src/AcmeCorp.Coyote.Data/Coyote.Data.GoogleBlobs/GoogleIndexedObjectStore.cs:line 700
   at AcmeCorp.Coyote.Data.GoogleBlobs.GoogleIndexedObjectStore`1.TryGetItemAndHeadAsync(OpContext op, String blobKey) in /Users/lukepuplett/Documents/Git/Coyote/src/AcmeCorp.Coyote.Data/Coyote.Data.GoogleBlobs/GoogleIndexedObjectStore.cs:line 293
   at AcmeCorp.Coyote.Features.Capture.BoxItemDeleter.DeleteOutboxItemAsync(OpContext op, String itemKey) in /Users/lukepuplett/Documents/Git/Coyote/src/AcmeCorp.Coyote.Web.Capture.Guts/Coyote.Features.Capture/BoxItemDeleter.cs:line 40
   at AcmeCorp.Coyote.Features.Capture.Coyote.Outbox.DeleteAsync(OpContext op, String itemKey) in /Users/lukepuplett/Documents/Git/Coyote/src/AcmeCorp.Coyote.Web.Capture.Guts/Coyote.Features.Capture.Coyote/Outbox.cs:line 125
   at AcmeCorp.Coyote.Features.Capture.Coyote.Outbox.EnactAsync(Act act) in /Users/lukepuplett/Documents/Git/Coyote/src/AcmeCorp.Coyote.Web.Capture.Guts/Coyote.Features.Capture.Coyote/Outbox.cs:line 298
   at AcmeCorp.Coyote.Features.Capture.CaptureCommandsImpl.EnactOutboxItemAsync(Act act) in /Users/lukepuplett/Documents/Git/Coyote/src/AcmeCorp.Coyote.Web.Capture.Guts/Coyote.Features.Capture/CaptureCommandsImpl.cs:line 277
   at AcmeCorp.Coyote.Features.Capture.Coyote.CoyoteController.PostCaptureCommand(PostCaptureCommandFormModel formModel) in /Users/lukepuplett/Documents/Git/Coyote/src/AcmeCorp.Coyote.Web.Capture.Guts/Coyote.Features.Capture.Coyote/CoyoteController.cs:line 156
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by jskeet** [comment]
Will look tomorrow.

**Comment by lukepuplett** [comment]
Hey Jon, I can see from the Google library code that this error is thrown when there is not error to deserialize. This is puzzling because either:

- Google's API is broken and this error is designed to indicate that there should be an error to deserialize.
- Google's API is working but the error "Error response is null" is unhelpful to the API user. It could fallback to using the HTTP status code, something like "The request was unsuccessful. No error information was available. HTTP status code: blah".

I'll try and repro it and check the status code in a moment. I've had to reboot as my debugger was in a mess.

**Comment by lukepuplett** [comment]
Okay I got it. I'm calling `GetBucketAsync` with the generation ID of the bucket I have cached. This is causing an HTTP `304 NotModified` to be returned. This correctly triggers exception handling but of course there's no error details.

I suggest improving the message to include the HTTP status code. The status would help developers find the cause quickly. Thanks.

**Comment by jskeet** [comment]
We'll have a look at including the status code - it should be in the `GoogleApiException` already of course, but I can see how putting it in the message (and probably saying "no body in error response" or similar rather than "Error response is null").

I'll move this issue into the appropriate repo, and change it to a feature request. This is a busy week internally, but we'll try to get to it soon.
