### ISSUE TITLE
When behind a VPN, does the .NET client Google.Cloud.SecretManager.V1 require extra CA cert configuration in addition to `core/custom_ca_certs_file`?

### ISSUE THREAD

**Issue by benfranklin79** [googleapis/google-cloud-dotnet#8315]
I've successfully authorized myself using the command:

```
gcloud auth login --update-adc
```

I'm working behind a Zscaler VPN and I've setup my CA cert using the key `core/custom_ca_certs_file`.
I've been able to access a secret using the following command:

```
gcloud secrets versions access "latest" --secret="some_key"
```

In my GCP application I'm using version 1.8.0 of Google.Cloud.SecretManager.V1

When running the following code in my application 

```
var client = SecretManagerServiceClient.Create();
var result = client.AccessSecretVersion(new SecretVersionName("some_project_id", "some_key", "latest"));
```

I get the following exception was thrown.

```
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1649171898.954000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1649171898.954000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":398,"grpc_status":14}]}")
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.SecretManager.V1.SecretManagerService.SecretManagerServiceClient.AccessSecretVersion(AccessSecretVersionRequest request, CallOptions options) in C:\projects\google-cloud-dotnet\apis\Google.Cloud.SecretManager.V1\Google.Cloud.SecretManager.V1\ServiceGrpc.g.cs:line 919
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
```

My question is this: is there some where else that I need to configure a CA certificate specifically for the .NET client. The fact that I am able to access the secret using the CLI but unable to acccess it via the application indicates one of :

1. CA cert configuration is missing (in addition to the one I've already configured above)
2. Zscaler is still blocking despite the certificate

Right now, I'm thinking it's unlikely that 2 is the case because secops are telling me they can see my CLI requests but unable to see
the requests from the application which suggests to me the cert handshake is failing for the .NET client - hence why I think it might be 1

**Comment by jskeet** [comment]
The client libraries make requests over HTTP/2 via Grpc.Core. Does ZScaler support HTTP/2?

If a different certificate needs to be used by the gRPC client, it's possible that setting the `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` environment variable to refer to a PEM file will help.

Note that gcloud uses (I believe) HTTP/1.1 and JSON rather than a gRPC connection - the different paths here would explain why the gcloud requests succeed but the client library ones fail.

Could you turn on gRPC logging and try again? Just set `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG` before running the code from the console, and you should see a *lot* of output, which will hopefully be helpful.

Apologies that this is a bit of a scattergun set of suggestions - the client library itself doesn't do anything low-level; it relies on the gRPC libraries to do that for us, so this is outside my area of expertise.

**Comment by jskeet** [comment]
@benfranklin79: Given the issue you've raised on the grpc repo, I'll close this now - I don't think we'd end up with any changes within this repo.
