### ISSUE TITLE
Docs release fails for IAM (alpha05)

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#8426]
Filing as process as it isn't a bug that will affect customers, beyond our ability to release.

The release build for #8423 is failing in the docs build with:

> [22-04-29 01:57:02.625]Warning:[ExtractMetadata](T:/src/github/google-cloud-dotnet/releasebuild/apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Iam.V1\Google.Cloud.Iam.V1\Google.Cloud.Iam.V1.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found.  T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Iam.V1\Google.Cloud.Iam.V1\Google.Cloud.Iam.V1.csproj

This is odd given that alpha02 released with no problems.

**Comment by jskeet** [comment]
Oddly, this works locally when running "builddocs.sh Google.Cloud.Iam.V1" directly in the docs directory, but fails in a subtly different way when running via buildrelease.sh:

> [22-04-29 02:45:20.175]Warning:[ExtractMetadata](C:/users/jonskeet/GitHub/googleapis/google-cloud-dotnet/releasebuild/apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\users\jonskeet\GitHub\googleapis\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Iam.V1\Google.Cloud.Iam.V1\Google.Cloud.Iam.V1.csproj' with message: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir)
   at Microsoft.DotNet.MSBuildSdkResolver.DotNetMSBuildSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext context, SdkResultFactory factory)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)

I suspect the two have the same cause though...

**Comment by jskeet** [comment]
Still failing now that we're targeting netstandard2.1 in the generated docfx JSON files. The nature of the error ("The SDK 'Microsoft.NET.Sdk' specified could not be found.") suggests it's an environmental issue, but I'm surprised that it all builds fine if that's the case - and that alpha02 was okay.

**Comment by jskeet** [comment]
We fixed this in the end by updating the CI machine.
