### ISSUE TITLE
System.DllNotFoundException: grpc_csharp_ext

### ISSUE THREAD

**Issue by OlivierMaire** [googleapis/google-cloud-dotnet#8457]
#### Environment details

  - OS: Windows / Android
  - .NET version: dotnet 6 / MAUI app
  - Package name and version: Google.Cloud.Firestore 2.5.0

#### Steps to reproduce

  1. Use the basic MAUI app template
  2. Add the nuget package Google.Cloud.Firestore
  3. Create a FirestoreDbBuilder object and call the Build function
```
		using var stream = await FileSystem.OpenAppPackageFileAsync("credentials.json");
		using var reader = new StreamReader(stream);
		var contents = reader.ReadToEnd();
		var builder = new FirestoreDbBuilder()
		{
			ProjectId = "my-project-id",
			JsonCredentials = contents
		};
		FirestoreDb db = builder.Build();
```

  5. The application works as a Windows App but not in Android App mode. (both in the x86_64 emulator and on a real device)

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: grpc_csharp_ext
[mono-rt]    at Grpc.Core.Internal.NativeLogRedirector.Redirect(NativeMethods native) in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeLogRedirector.cs:line 49
[mono-rt]    at Grpc.Core.Internal.NativeExtension..ctor() in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeExtension.cs:line 46
[mono-rt]    at Grpc.Core.Internal.NativeExtension.Get() in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeExtension.cs:line 67
[mono-rt]    at Grpc.Core.Internal.NativeMethods.Get() in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/NativeMethods.cs:line 49
[mono-rt]    at Grpc.Core.GrpcEnvironment.GrpcNativeInit() in /var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs:line 373
[mono-rt]    at Grpc.Core.GrpcEnvironment..ctor() in /var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs:line 302
[mono-rt]    at Grpc.Core.GrpcEnvironment.AddRef() in /var/local/git/grpc/src/csharp/Grpc.Core/GrpcEnvironment.cs:line 78
[mono-rt]    at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options) in /var/local/git/grpc/src/csharp/Grpc.Core/Channel.cs:line 70
[mono-rt]    at Google.Api.Gax.Grpc.GrpcCore.GrpcCoreAdapter.CreateChannelImpl(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options) in /_/Google.Api.Gax.Grpc.GrpcCore/GrpcCoreAdapter.cs:line 35
[mono-rt]    at Google.Api.Gax.Grpc.GrpcAdapter.CreateChannel(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options) in /_/Google.Api.Gax.Grpc/GrpcAdapter.cs:line 29
[mono-rt]    at Google.Api.Gax.Grpc.ClientBuilderBase`1[[Google.Cloud.Firestore.V1.FirestoreClient, Google.Cloud.Firestore.V1, Version=2.5.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0]].CreateChannel(String endpoint, ChannelCredentials credentials) in /_/Google.Api.Gax.Grpc/ClientBuilderBase.cs:line 490
[mono-rt]    at Google.Api.Gax.Grpc.ClientBuilderBase`1[[Google.Cloud.Firestore.V1.FirestoreClient, Google.Cloud.Firestore.V1, Version=2.5.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0]].CreateCallInvoker() in /_/Google.Api.Gax.Grpc/ClientBuilderBase.cs:line 319
[mono-rt]    at Google.Cloud.Firestore.V1.FirestoreClientBuilder.BuildImpl() in /_/apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClient.g.cs:line 398
[mono-rt]    at Google.Cloud.Firestore.V1.FirestoreClientBuilder.Build() in /_/apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClient.g.cs:line 384
[mono-rt]    at Google.Cloud.Firestore.FirestoreDbBuilder.Build() in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/FirestoreDbBuilder.cs:line 98
[mono-rt]    at iot_garden.SettingPage.OnCounterClicked(Object sender, EventArgs e) in C:\Users\Fuyuki\src\iot-garden\SettingPage.xaml.cs:line 33
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

**Comment by jskeet** [comment]
Basically, Android isn't a supported platform for our client libraries at the moment.

It's *possible* that you could get this to work using Grpc.Net.Client, and in a couple of weeks we'll be releasing a new major version of all libraries which uses Grpc.Net.Client by default, but I still don't expect we'll actively support Android, even via MAUI.

**Comment by jskeet** [comment]
If you want to test it at the moment, you could *try* adding the Google.Api.Gax.Grpc.GrpcNetClient package, and then use:

```csharp
var builder = new FirestoreDbBuilder()
{
    ProjectId = "my-project-id",
    GrpcAdapter = GrpcNetClientAdapter.Default,
    JsonCredentials = contents
};
```

**Comment by OlivierMaire** [comment]
I could test the workaround and connect to the Firestore, thank you!

I am aware  of the problem of storing the credentials on the client side and plan to have another way of managing the credentials later.
