### ISSUE TITLE
map an array of objects from Cloud Firestore 

### ISSUE THREAD

**Issue by Aronastu** [googleapis/google-cloud-dotnet#8554]
map an array of objects from Cloud Firestore to a List of objects
ConvertTo method through error,
```
 [FirestoreData]
public class ExpenseArray
    {

        [FirestoreProperty]
        public DateTime date {get; set; }
        [FirestoreProperty]
        public string sender_tin_no { get; set; }
        [FirestoreProperty]
        public double total_paid { get; set; }
        [FirestoreProperty]
        public double vat_paid { get; set; }
    }


    public class ExpenseArrayList
    {
        [FirestoreProperty]
        public List<ExpenseArray> Info { get; set; }
    }
```
then 
```
DocumentSnapshot snap = await docRef.GetSnapshotAsync();

                if (snap.Exists)
                {
                    ExpenseArrayList expenses = snap.ConvertTo<ExpenseArrayList>(); // through error (unable)
                }
```

**Comment by jskeet** [comment]
Please give exact details of the error. Is it a compile-time error or an execution-time error? What's the error message, and if it's an exception, what does the stack trace look like?

What does your data look like?

**Comment by Aronastu** [comment]
data look 👍 https://ibb.co/D1vDgWt
it is exception :Unable to create converter for type RMS.Fire_Base.ExpenseArrayList

its stack trace
```
   at Google.Cloud.Firestore.Converters.ConverterCache.CreateConverter(Type targetType) in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/ConverterCache.cs:line 133
   at Google.Cloud.Firestore.Converters.ConverterCache.<>c.<GetConverter>b__1_0(Type t) in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/ConverterCache.cs:line 69
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Google.Cloud.Firestore.Converters.ConverterCache.GetConverter(Type targetType) in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/ConverterCache.cs:line 69
   at Google.Cloud.Firestore.SerializationContext.GetConverter(Type targetType) in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/SerializationContext.cs:line 44
   at Google.Cloud.Firestore.DeserializationContext.GetConverter(Type targetType) in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/DeserializationContext.cs:line 51
   at Google.Cloud.Firestore.ValueDeserializer.DeserializeMap(DeserializationContext context, IDictionary`2 values, Type targetType) in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/ValueDeserializer.cs:line 76
   at Google.Cloud.Firestore.DocumentSnapshot.ConvertTo[T]() in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/DocumentSnapshot.cs:line 102
   at RMS.Retrieve.<getExpenseArray>d__9.MoveNext() in C:\Users\Arona\source\repos\RMS\RMS\Retrieve.cs:line 335
```

**Comment by jskeet** [comment]
Your `ExpenseArrayList` class doesn't have the `[FirestoreData]` attribute on it - perhaps that's all that's wrong? Please add it and try again - if that's not it, I'll try to reproduce the issue when I get a chance.

**Comment by Aronastu** [comment]
jskeet, Thanks alot, now its working
