### ISSUE TITLE
no send request for reporting

### ISSUE THREAD

**Issue by esantos22** [googleapis/google-cloud-dotnet#8775]
**program:** 
 public ActionResult SampleRunReport() => SampleRunReport("262100326");
        ActionResult SampleRunReport(string propertyId)
        {
            try
            {

                var path = Directory.GetCurrentDirectory();
                string credential_path = @"/config/testappapiga.json";
                var file = path + credential_path;
                
                System.Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", file);

                /**
              * TODO(developer): Uncomment this variable and replace with your
              *  Google Analytics 4 property ID before running the sample.
              */
                // propertyId = "YOUR-GA4-PROPERTY-ID";

                // Using a default constructor instructs the client to use the credentials
                // specified in GOOGLE_APPLICATION_CREDENTIALS environment variable.
                BetaAnalyticsDataClient client = BetaAnalyticsDataClient.Create();

                // Initialize request argument(s)
                RunReportRequest request = new RunReportRequest
                {
                    Property = "properties/" + propertyId,
                    Dimensions = { new Dimension { Name = "operatingSystem" }, },
                    Metrics = { new Metric { Name = "users" }, new Metric { Name = "sessions" } },
                    DateRanges = { new DateRange { StartDate = "2022-05-31", EndDate = "today" }, },
                };

                // Make the request
                var response = client.RunReport(request);

                Console.WriteLine("Report result:");
                foreach (Row row in response.Rows)
                {
                    Console.WriteLine("{0}, {1}", row.DimensionValues[0].Value, row.MetricValues[0].Value);
                }

                Debug.WriteLine("Exitooo!!!");
                return Ok("Exitooo!!!");
            }
            catch (Exception ex)
            {
                var msgEx = ex.Message + '\n' + ex.StackTrace;

                Debug.WriteLine(msgEx);
                return BadRequest(msgEx);
            }
        }

**log error**
Status(StatusCode="DeadlineExceeded", Detail="")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Analytics.Data.V1Beta.BetaAnalyticsData.BetaAnalyticsDataClient.RunReport(RunReportRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass12_0.<WithCallSettingsOverlay>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Analytics.Data.V1Beta.BetaAnalyticsDataClientImpl.RunReport(RunReportRequest request, CallSettings callSettings)

**Comment by jskeet** [comment]
Please could you add some logging so you can tell us how long the RPC has been running for before timing out? It looks like the RPC has a 1 minute default timeout.

If you want to try with a longer timeout, you could change this:

```csharp
var response = client.RunReport(request);
```

to

```csharp
var expiration = Expiration.FromTimeout(TimeSpan.FromMinutes(5));
var response = client.RunReport(request, CallSettings.FromExpiration(expiration));
```

**Comment by jskeet** [comment]
Closing due to lack of information. If you're still running into problems, please provide more information and we can reopen the issue.
