### ISSUE TITLE
How do I create Avro file from BigQuery stream

### ISSUE THREAD

**Issue by s-vitaliy** [googleapis/google-cloud-dotnet#8833]
I'm trying to download data from BigQuery table and save it to an avro file for further processing.

As a response I'm getting an object that contains field Arrows.Serialized Binary Rows. Is it possible to write this rows to file, but not deserialize them into objects?

How could I do that?  I [read an example in avro faq](https://cwiki.apache.org/confluence/display/AVRO/FAQ#FAQ-HowcanIserializedirectlyto/fromabytearray?), but it seems, Apache library designed to write files from objects, not to create file form serialized rows, that big query returns to me.

**Comment by s-vitaliy** [comment]
@jskeet, I'm using Google.Cloud.BigQuery.Storage.V1 for downloading data. I want to write data to file.

I tried to write into a file SerializedBinaryRows and read it by the spark-avro module, but it seems that it is not correct way to save data into a file, am I right?

```csharp
BigQueryReadClient client = BigQueryReadClient.Create();
private static CreateReadSessionRequest CreateReadSessionRequest(TableReference reference)
{
    return new CreateReadSessionRequest()
    {
        Parent = $"projects/{reference.ProjectId}",
        ReadSession = new ReadSession
        {
             Table = $"projects/{reference.ProjectId}/datasets/{reference.DatasetId}/tables/{reference.TableId}",
             DataFormat = DataFormat.Avro,
        },
        MaxStreamCount = 1
    };
}


var stream = this.bigQueryReadClient.ReadRows(session.Streams[0].Name, 0).GetResponseStream();

await foreach (var item in stream)
{
    var byteArray = item.AvroRows.SerializedBinaryRows.ToByteArray();
    File.WriteAllBytes("myfile.avro", byteArray);     // I want to write this byte array to file somehow
}

**Comment by jskeet** [comment]
Well currently you're writing multiple byte strings to the same file, but apart from that I'd expect it to work. When you say "it seems that it is not correct way to save data into a file" that suggests you've encountered problems with the code, but you haven't told us what problems you're actually seeing.

**Comment by s-vitaliy** [comment]
When I'm trying to read this from pyspark session with the following command
` df = spark.read.format("avro").load(...)`, I'm getting the error: `org.apache.avro.InvalidAvroMagicException: Not an Avro data file`, you can see full stacktrace below. That's why I think, I'm using your API wrong and need help to figure out, how can I create avro files.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/bitnami/spark/python/pyspark/sql/readwriter.py", line 158, in load
    return self._df(self._jreader.load(path))
  File "/opt/bitnami/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1321, in __call__
  File "/opt/bitnami/spark/python/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/opt/bitnami/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o89.load.
: org.apache.spark.SparkException: Could not read file: <...>
        at org.apache.spark.sql.avro.AvroUtils$.$anonfun$inferAvroSchemaFromFiles$3(AvroUtils.scala:149)
        at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2713)
        at org.apache.spark.sql.avro.AvroUtils$.$anonfun$inferAvroSchemaFromFiles$1(AvroUtils.scala:140)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:180)
        at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:167)
        at scala.collection.AbstractIterator.collectFirst(Iterator.scala:1431)
        at org.apache.spark.sql.avro.AvroUtils$.inferAvroSchemaFromFiles(AvroUtils.scala:154)
        at org.apache.spark.sql.avro.AvroUtils$.$anonfun$inferSchema$2(AvroUtils.scala:60)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.avro.AvroUtils$.inferSchema(AvroUtils.scala:59)
        at org.apache.spark.sql.avro.AvroFileFormat.inferSchema(AvroFileFormat.scala:57)
        at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:210)
        at scala.Option.orElse(Option.scala:447)
        at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:207)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:411)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:188)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.avro.InvalidAvroMagicException: Not an Avro data file
        at org.apache.avro.file.DataFileReader.openReader(DataFileReader.java:79)
        at org.apache.spark.sql.avro.AvroUtils$.$anonfun$inferAvroSchemaFromFiles$3(AvroUtils.scala:142)
        ... 32 more

**Comment by jskeet** [comment]
Okay, at this point I'll hand over to @Rishabh-V who I believe has worked with the Avro side of things and had it working. I know very little about Avro myself, but that looks like the right way to write the data file (other than writing each block to a separate file).

**Comment by Rishabh-V** [comment]
I am looking into this now and will write a sample app. Will update here once done but it will be likely tomorrow.

**Comment by jskeet** [comment]
Okay, I've had another look at this, and I believe I understand it now.

The `SerializedBinaryRows` binary data isn't a complete Avro file - it's just a sequence of records.

However, it's reasonably straightforward to use the schema provided in the session to read all the records and create a single file from them. Here's some sample code which has produced what at least looks like a valid Avro data file to me (and works with https://zymeworks.github.io/avro-viewer/ as a quick test).

```csharp
BigQueryReadClient client = BigQueryReadClient.Create();

// Start the session, including fetching the schema.
var request = new CreateReadSessionRequest()
{
    ParentAsProjectName = new ProjectName(projectId),
    ReadSession = new ReadSession
    {
        TableAsTableName = new TableName(projectId, datasetId, tableId),
        DataFormat = DataFormat.Avro,
    },
    MaxStreamCount = 1
};
var session = client.CreateReadSession(request);

// We can now create a generic record reader based on the schema.
var schema = Schema.Parse(session.AvroSchema.Schema);
GenericDatumReader<GenericRecord> reader = new GenericDatumReader<GenericRecord>(schema, schema);

// Read the rows as a stream. Each response can contain multiple rows, but we write everything
// into a single file.
var stream = client.ReadRows(session.Streams[0].Name, 0).GetResponseStream();
using var output = File.Create("data.avro");
using var writer = DataFileWriter<GenericRecord>.OpenWriter(new GenericDatumWriter<GenericRecord>(schema), output);
await foreach (var item in stream)
{
    // The item.AvroRows.SerializedBinaryRows is just a sequence of
    // records which we can read from one at a time.
    // We use item.RowCount to determine how many records to read.        

    // Note: creating a copy of the data is inefficient, but simple.
    // Using Microsoft.Toolkit.HighPerformance we could probably use
    // var stream = item.AvroRows.SerializedBinaryRows.AsMemory().AsStream()
    var byteArray = item.AvroRows.SerializedBinaryRows.ToByteArray();
    var decoder = new BinaryDecoder(new MemoryStream(byteArray));

    // Once we've got the decoder, we can just append each record to the writer.
    for (int i = 0; i < item.RowCount; i++)
    {
        var record = reader.Read(null!, decoder);
        writer.Append(record);
    }
}
```
