### ISSUE TITLE
How to parse BigQuery Audit Log

### ISSUE THREAD

**Issue by AlonShitrit** [googleapis/google-cloud-dotnet#8963]
I'm writing a program that reads logs and runs some logic on them.
Some of these logs are generated by BigQuery.
Unfortunately, I'm unable to parse Log Entries which contain BigQuery service data.

I'm initializing the parser as follows - 
```
var registry =
  TypeRegistry.FromMessages(
      Enumerable.Empty<MessageDescriptor>().
          Concat(
              AuditDataReflection.Descriptor.MessageTypes,
              AuditLogReflection.Descriptor.MessageTypes,
              BigqueryAuditMetadataReflection.Descriptor.MessageTypes,
              Google.Rpc.CodeReflection.Descriptor.MessageTypes,
              Google.Rpc.ErrorDetailsReflection.Descriptor.MessageTypes,
              Google.Rpc.StatusReflection.Descriptor.MessageTypes,
              LoggingReflection.Descriptor.MessageTypes
          )
  );
var settings =
  JsonParser.Settings.Default.
      WithTypeRegistry(registry).
      WithIgnoreUnknownFields(true);
var parser = new JsonParser(settings);
...
...
...
var logEntry = parser.Parse<LogEntry>(logEntryString);
```

And I'm getting the following error - 
```
System.InvalidOperationException: Type registry has no descriptor for type name 'google.cloud.bigquery.logging.v1.AuditData'
   at Google.Protobuf.JsonParser.MergeAny(IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.<>c.<.cctor>b__41_6(JsonParser parser, IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.Merge(IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.ParseSingleValue(FieldDescriptor field, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.MergeField(IMessage message, FieldDescriptor field, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.Merge(IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.MergeAny(IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.<>c.<.cctor>b__41_6(JsonParser parser, IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.Merge(IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.ParseSingleValue(FieldDescriptor field, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.MergeField(IMessage message, FieldDescriptor field, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.Merge(IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.Merge(IMessage message, TextReader jsonReader)
   at Google.Protobuf.JsonParser.Parse[T](TextReader jsonReader)
   at Google.Protobuf.JsonParser.Parse[T](String json)
```

Is there some descriptor I've missed? is there a workaround so at least an exception won't be thrown?

Thanks in advance,
Alon

**Comment by AlonShitrit** [comment]
Thanks for the quick response.

In the meanwhile is there any workaround I can use to just avoid deserializing the serviceData property?

**Comment by jskeet** [comment]
Not at the moment, I'm afraid. The Protobuf and client libraries teams are collaborating on making the JSON format easier to work with, but currently there's no way of just ignoring a google.protobuf.Any that represents a type that's not available.

Depending on what you're trying to do with the log entries, you *may* find it easier just to parse them as JObject using Newtonsoft.Json for example.

**Comment by AlonShitrit** [comment]
got it, thanks

**Comment by jskeet** [comment]
We've now published the Google.Cloud.BigQuery.Logging.V1 package. If you add a dependency on that, and use the code from my earlier comment, it should all work for you. Thanks for raising the issue, and please don't hesitate to let us know if you encounter further problems.
