### ISSUE TITLE
Method not found: 'Void Google.Api.Gax.Grpc.ClientBuilderBase`1..ctor()'.

### ISSUE THREAD

**Issue by lukepuplett** [googleapis/google-cloud-dotnet#9066]
Hello, I've recently been updating some .NET GCP NuGet packages I depend on to latest versions.

These are the packages and versions I'm using (gathered from across my solution's projects).

| Package                                        | Version       |
|------------------------------------------------|---------------|
| Google.Cloud.AspNetCore.DataProtection.Kms     | 1.0.0-alpha03 |
| Google.Cloud.AspNetCore.DataProtection.Storage | 1.0.0-alpha03 |
| Google.Cloud.Diagnostics.AspNetCore3           | 5.0.0         |
| Google.Cloud.Firestore                         | 3.0.0         |
| Google.Cloud.Storage.V1                        | 4.1.0         |

AFAIK the Firestore package has breaking changes regarding GAX v4 and GRPC.

https://github.com/googleapis/google-cloud-dotnet/issues/9033#issue-1352284831

When deployed to production Cloud Run, my app fails to run, emitting the following error. Have I introduced an incompatibility between Google's libraries?

```
Unhandled exception. System.MissingMethodException: Method not found: 'Void Google.Api.Gax.Grpc.ClientBuilderBase`1..ctor()'.
 at Google.Cloud.Kms.V1.KeyManagementServiceClientBuilder..ctor()
 at Microsoft.AspNetCore.DataProtection.GoogleCloudDataProtectionBuilderExtensions.<>c__DisplayClass3_0.<ProtectKeysWithGoogleKms>b__0(IServiceProvider services)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
 at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
 at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
 at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
 at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
 at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
 at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
 at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
 at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
 at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
 at AcmeCorp.CoyoteTrap.Framework.Hosting.Program.Main(String[] args) in /src/AcmeCorp.CoyoteTrap.AspNetCoreMvc/CoyoteTrap.Framework.Hosting/Program.cs:line 19
```

**Comment by lukepuplett** [comment]
For clarity, this fails in production simply because the following code, which leads to the error, is conditional on the production environment. I can fudge it so it repros on my Macbook, too.

    services.AddDataProtection().PersistKeysToGoogleCloudStorage(a, b).ProtectKeysWithGoogleKms(c);

**Comment by amanda-tarafa** [comment]
This is basically a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-dotnet-powerpack/issues/28. We are looking into it.
I'll close this one in favour of the other one, do feel free to leave a comment here  if you believe there's something else involved.

**Comment by jskeet** [comment]
Just in case you didn't subscribe to that issue: I've just published 1.0.0-alpha04 versions of both of the Data Protection libraries, which should solve this problem.

**Comment by lukepuplett** [comment]
Jon, Amanda; huge thanks for the thoughtful heads-up and the turn around on this problem. This 04 is looking good, my deployed instances are up and running.

**Comment by abelbraaksma** [comment]
Not sure what happened meanwhile, but this seems to be still happening. I got the following:

```
System.MissingMethodException: Method not found: 'Void Google.Api.Gax.Grpc.ClientBuilderBase`1..ctor()'.
   at Google.Cloud.Trace.V1.TraceServiceClientBuilder..ctor()
   at Google.Cloud.Trace.V1.TraceServiceClient.Create()
   at Google.Cloud.Diagnostics.Common.TraceExtensions.AddGoogleTrace(IServiceCollection services, TraceServiceOptions options)
   at Google.Cloud.Diagnostics.Common.GoogleDiagnosticsExtensions.AddGoogleDiagnostics(IServiceCollection services, TraceServiceOptions traceOptions, LoggingServiceOptions loggingOptions, ErrorReportingServiceOptions errorReportingOptions)
   at Google.Cloud.Diagnostics.Common.GoogleDiagnosticsExtensions.AddGoogleDiagnostics(IServiceCollection services, String projectId, String serviceName, String serviceVersion, TraceOptions traceOptions, LoggingOptions loggingOptions, ErrorReportingOptions errorReportingOptions)
   at Lula.AccountManagement.Http.GoogleCloudDiagnostics.configureServices(IServiceCollection services) in /build/src/Lula.AccountManagement.Http/Logging.fs:line 24
   at Lula.AccountManagement.Http.App.configureServices(WebApplicationBuilder builder) in /build/src/Lula.AccountManagement.Http/App.fs:line 121
   at Lula.AccountManagement.Http.Program.main(String[] args) in /build/src/Lula.AccountManagement.Http/Program.fs:line 10
```

Looks like dependencies are not automatically resolved. I'll see if there's a more recent issue tracking this, but figured I'd let people know that this is still happening.

**Comment by jskeet** [comment]
@abelbraaksma: Please file a new issue with more details. It seems very unlikely that an issue from 3 years ago is going to be relevant unless you're using *really* old (and mismatched) dependencies. We don't have enough information with just a stack trace and no other information.
