### ISSUE TITLE
Datastore CI tests failing

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#9888]
We're seeing this test failure internally in CI - although I can't reproduce it locally:

```text
Google.Cloud.Datastore.V1.IntegrationTests.DatastoreTransactionTest.Transaction_WithCount [FAIL]
  Failed Google.Cloud.Datastore.V1.IntegrationTests.DatastoreTransactionTest.Transaction_WithCount [613 ms]
  Error Message:
   Grpc.Core.RpcException : Status(StatusCode="InvalidArgument", Detail="queries inside transactions must have ancestors")
...
   at Google.Cloud.Datastore.V1.DatastoreClientImpl.RunAggregationQuery(RunAggregationQueryRequest request, CallSettings callSettings) in ...\DatastoreClient.g.cs:line 1239
   at Google.Cloud.Datastore.V1.DatastoreTransactionImpl.RunAggregationQuery(AggregationQuery query, CallSettings callSettings) in ...\DatastoreTransactionImpl.cs:line 136
   at Google.Cloud.Datastore.V1.IntegrationTests.DatastoreTransactionTest.Transaction_WithCount() in ...\DatastoreTransactionTest.cs:line 172
```

(There's more stack trace, but it's not terribly useful.)

I haven't yet looked at whether it's easy to change the given query to include an ancestor.

**Comment by hemanshv** [comment]
Signing off for the day. Will check it as first thing tomorrow and will get back.
Thanks,

**Comment by jskeet** [comment]
Righto, no problem.
